
Runner.Event=Runner.extend(Runner.emptyFn,{events:null,listeners:null,elemsForEvent:null,suspendedEvents:null,constructor:function(){this.listeners=[];this.elemsForEvent=[];this.suspendedEvents=[];},init:function(){if(this.events.length==0){return false;}
for(var i=0;i<this.events.length;i++){this.on(this.events[i],this[this.events[i]]);}
return true;},suspendEvent:function(eventArr){for(var i=0;i<eventArr.length;i++){if(!this.suspendedEvents.isInArray(eventArr[i])){this.suspendedEvents.push(eventArr[i]);}}},resumeEvent:function(eventArr){var eventInd=-1;for(var i=0;i<eventArr.length;i++){eventInd=this.suspendedEvents.getIndexOfElem(eventArr[i]);if(eventInd!=-1){this.suspendedEvents.splice(eventInd,1);}}},createDelayed:function(handler,timeout){return function(e){setTimeout(function(){handler(e);},timeout||10);};},createBuffered:function(handler,buffer){var task=new Runner.util.DelayedTask(handler);return function(e){task.delay(buffer,handler,null,[e]);};},createSingle:function(handler,eventName){var obj=this;return function(e){handler(e);obj.clearEvent(eventName);};},on:function(eventName,fn,options,scope){if(!this.elemsForEvent.length||!fn){return false;}
this.addEvent([eventName]);var onEventName="";if(eventName.indexOf("on",0)==0){onEventName=eventName;eventName=eventName.substring(2);}else{onEventName="on"+eventName;}
var scope=scope?scope:this,objScope=this,options=options?options:{};var args=options.args?options.args:[],single=options.single?options.single:false,timeout=options.timeout?options.timeout:0,buffer=options.buffer?options.buffer:0;var callHandler=function(e){if(objScope.suspendedEvents.isInArray(eventName)){return;}
fn.call(scope,e,args);}
if(timeout){this.createDelayed(callHandler,timeout);}
if(single){this.createSingle(callHandler,eventName)}
if(buffer){this.createBuffered(callHandler,buffer);}
var listener=this.getListener(eventName);if(!listener){this.listeners.push({name:eventName,handler:fn,callHandler:callHandler,options:options,scope:scope,index:this.listeners.length});}else{this.listeners[listener.index].handler=fn;this.listeners[listener.index].callHandler=callHandler;this.listeners[listener.index].options=options;this.listeners[listener.index].scope=scope;}
for(var i=0;i<this.elemsForEvent.length;i++){var el=this.elemsForEvent[i];$(el).bind(eventName,callHandler);}
return true;},addEvent:function(eventNameArr){if(!this.events){this.events=[];}
this.addEvent=function(eventNameArr){for(var i=0;i<eventNameArr.length;i++){if(!this.events.isInArray(eventNameArr[i])){this.events.push(eventNameArr[i]);}}}
this.addEvent(eventNameArr);},killEvent:function(eventName){var eventInd=this.events.getIndexOfElem(eventName);if(eventInd===-1){return false;}
var listener=this.getListener(eventName);if(!listener){return false;}
for(var j=0;j<this.elemsForEvent.length;j++){var el=this.elemsForEvent[j];$(el).unbind(eventName,listener.callHandler);}
this.listeners.splice(j,1);delete this[eventName];this.events.splice(eventInd,1);return true;},clearEvent:function(eventName){var eventInd=this.events.getIndexOfElem(eventName);if(eventInd===-1){return false;}
var listener=this.getListener(eventName);if(!listener){return false;}
for(var j=0;j<this.elemsForEvent.length;j++){var el=this.elemsForEvent[j];$(el).unbind(eventName,listener.callHandler);}
this.on(eventName);return true;},stopEvent:function(e){this.stopPropagation(e);this.preventDefault(e);},stopPropagation:function(e){e=this.getEvent(e);if(e&&e.stopPropagation){e.stopPropagation();}else if(e){e.cancelBubble=true;}},preventDefault:function(e){e=this.getEvent(e);if(e&&e.preventDefault){e.preventDefault();}else if(e){e.returnValue=false;}},getEvent:function(e){return e||window.event;},getTarget:function(e){if(e){return e.target||e.srcElement;}},fireEvent:function(eventName){var eventIndex=this.isDefinedEvent(eventName);if(eventIndex===-1){return false;}
var listener=this.getListener(eventName);if(listener===false){return false;}
listener.callHandler.apply(this,[null].concat(Array.prototype.slice.call(arguments,1)));if(this[eventName]){this[eventName].apply(this,[null].concat(Array.prototype.slice.call(arguments,1)));}
return true;},isDefinedEvent:function(eventName){return this.events.getIndexOfElem(eventName);},getListener:function(eventName){for(var i=0;i<this.listeners.length;i++){if(this.listeners[i].name==eventName){return this.listeners[i];}}
return false;}});validation={validatorConsts:{predefined:1,user:2,notFound:3},userValidators:[],predefinedValidatorsArr:['isrequired','isnumeric','ispassword','isemail','ismoney','iszipcode','isphonenumber','isstate','isssn','iscc','istime','isdate','regexp'],validate:function(validArr,control){var validationRes=false,validatorStatus,result={result:true,messageArr:[]};for(var i=0;i<validArr.length;i++){if(!validArr[i]){continue;}
validatorStatus=this.getValidatorStatus(validArr[i]);if(validatorStatus==this.validatorConsts.user){validationRes=window[control.validationArr[i]](control.getValue());}else if(validatorStatus==this.validatorConsts.predefined){if(validArr[i]=="IsRequired"){if(control.isEmpty()){validationRes=TEXT_INLINE_FIELD_REQUIRED;}else{validationRes=true;}}else{validationRes=this[validArr[i]](control.getValue(),control.regExp);}}else{validationRes=true;}
result=this.setResult(validationRes,result);}
return result;},getValidatorStatus:function(validatorName){if(this.predefinedValidatorsArr.isInArray(validatorName)){return this.validatorConsts.predefined;}else if(window[validatorName]&&((typeof(window[validatorName])=='function')||(Runner.isIE&&typeof(window[validatorName])=='object'))){return this.validatorConsts.user;}else{return this.validatorConsts.notFound;}},setResult:function(res,obj){var len=obj.messageArr.length;if(res!==true){obj.result=false;if(typeof(res)=='object'){for(var i=0;i<res.length;i++){obj.messageArr.push(res[i]);}}else{obj.messageArr.push(res);}}
return obj;},registerCustomValidation:function(ctrl){var validatorStatus;for(var i=0;i<ctrl.validationArr.length;i++){if(!ctrl.validationArr[i]){continue;}
validatorStatus=this.getValidatorStatus(ctrl.validationArr[i]);if(validatorStatus==this.validatorConsts.user||validatorStatus==this.validatorConsts.notFound){var isAdded=false;for(var j=0;j<this.userValidators.length;j++){if(this.userValidators[j]==ctrl.validationArr[i]){isAdded=true;break;}}
if(!isAdded){Runner.loadJS('include/validate/'+ctrl.validationArr[i]+'.js');this.userValidators.push(ctrl.validationArr[i]);}}}},"IsRequired":function(sVal)
{var regexp=/.+/;if(typeof(sVal)!='string')
sVal=sVal.toString();if(!sVal.match(regexp)&&!this.setRequired)
{this.setRequired=true;return TEXT_INLINE_FIELD_REQUIRED;}
else
return true;},"IsNumeric":function(sVal)
{sVal=sVal.replace(/,/g,"");if(isNaN(sVal))
return TEXT_INLINE_FIELD_NUMBER;else
return true;},"IsPassword":function(sVal)
{var regexp1=/^password$/;var regexp2=/.{4,}/;if(sVal.match(regexp1))
return TEXT_INLINE_FIELD_PASSWORD1;else if(!sVal.match(regexp2))
return TEXT_INLINE_FIELD_PASSWORD2;else
return true;},"IsEmail":function(sVal)
{var regexp=/^[A-z0-9_-]+([.][A-z0-9_-]+)*[@][A-z0-9_-]+([.][A-z0-9_-]+)*[.][A-z]{2,4}$/;if(sVal.match(/.+/)&&!sVal.match(regexp))
return TEXT_INLINE_FIELD_EMAIL;else
return true;},"IsMoney":function(sVal)
{var regexp=/^(\d*)\.?(\d*)$/;if(sVal.match(/.+/)&&!sVal.match(regexp))
return TEXT_INLINE_FIELD_CURRENCY;else
return true;},"IsZipCode":function(sVal)
{var regexp=/^\d{5}([\-]\d{4})?$/;if(sVal.match(/.+/)&&!sVal.match(regexp))
return TEXT_INLINE_FIELD_ZIPCODE;else
return true;},"IsPhoneNumber":function(sVal)
{var regexp=/^\(\d{3}\)\s?\d{3}\-\d{4}$/;var stripped=sVal.replace(/[\(\)\.\-\ ]/g,'');if(sVal.match(/.+/)&&(isNaN(parseInt(stripped))||stripped.length!=10))
return TEXT_INLINE_FIELD_PHONE;else
return true;},"IsState":function(sVal)
{if(sVal.match(/.+/)&&!arrStates.inArray(sVal,false))
return TEXT_INLINE_FIELD_STATE;else
return true;},"IsSSN":function(sVal)
{var regexp=/^\d{3}(-|\s)\d{2}(-|\s)\d{4}$/;if(sVal.match(/.+/)&&!sVal.match(regexp))
return TEXT_INLINE_FIELD_SSN;else
return true;},"IsCC":function(sVal)
{var regexp=/^((4\d{3})|(5[1-5]\d{2}))(-?|\040?)(\d{4}(-?|\040?)){3}|^(3[4,7]\d{2})(-?|\040?)\d{6}(-?|\040?)\d{5}/;if(sVal.match(/.+/)&&!sVal.match(regexp))
return TEXT_INLINE_FIELD_CC;else
return true;},"IsTime":function(sVal)
{var regexp=/\d+/g;if(!sVal)
return true;var arr=sVal.match(regexp);var bFlag=true;if(arr==null||arr.length>3)
bFlag=false;while(bFlag&&arr.length<3)
arr[arr.length]=0;if(bFlag&&(arr[0]<0||arr[0]>23||arr[1]<0||arr[1]>59||arr[2]<0||arr[2]>59))
bFlag=false;if(!bFlag)
return TEXT_INLINE_FIELD_TIME;else
return true;},"IsDate":function(sVal)
{var fmt="";switch(locale_dateformat)
{case 0:fmt="MDY";break;case 1:fmt="DMY";break;default:fmt="YMD";break;};if(!this.isValidDate(sVal,fmt))
return TEXT_INLINE_FIELD_DATE;else
return true;},"RegExp":function(sVal,regExpParamsObj){var re=new RegExp(regExpParamsObj.regex);if(!re.test(sVal)||re.exec(sVal)[0]!=sVal){if(regExpParamsObj.messagetype=='Text'){return regExpParamsObj.message;}else{return GetCustomLabel(regExpParamsObj.message);}}else{return true;}},isValidDate:function(dateStr,format){if(format==null)
format="MDY";format=format.toUpperCase();if(format.length!=3)
format="MDY";if((format.indexOf("M")==-1)||(format.indexOf("D")==-1)||(format.indexOf("Y")==-1))
format="MDY";if(format.substring(0,1)=="Y")
{var reg1=/^\d{2}(\-|\/|\.)\d{1,2}\1\d{1,2}$/;var reg2=/^\d{4}(\-|\/|\.)\d{1,2}\1\d{1,2}$/;}
else if(format.substring(1,2)=="Y")
{var reg1=/^\d{1,2}(\-|\/|\.)\d{2}\1\d{1,2}$/;var reg2=/^\d{1,2}(\-|\/|\.)\d{4}\1\d{1,2}$/;}
else{var reg1=/^\d{1,2}(\-|\/|\.)\d{1,2}\1\d{2}$/;var reg2=/^\d{1,2}(\-|\/|\.)\d{1,2}\1\d{4}$/;}
if((reg1.test(dateStr)==false)&&(reg2.test(dateStr)==false))
return false;var parts=dateStr.split(RegExp.$1);if(format.substring(0,1)=="M")
var mm=parts[0];else if(format.substring(1,2)=="M")
var mm=parts[1];else
var mm=parts[2];if(format.substring(0,1)=="D")
var dd=parts[0];else if(format.substring(1,2)=="D")
var dd=parts[1];else
var dd=parts[2];if(format.substring(0,1)=="Y")
var yy=parts[0];else if(format.substring(1,2)=="Y")
var yy=parts[1];else
var yy=parts[2];if(parseFloat(yy)<=50)
yy=(parseFloat(yy)+2000).toString();if(parseFloat(yy)<=99)
yy=(parseFloat(yy)+1900).toString();var dt=new Date(parseFloat(yy),parseFloat(mm)-1,parseFloat(dd),0,0,0,0);if(parseFloat(dd)!=dt.getDate())
return false;if(parseFloat(mm)-1!=dt.getMonth())
return false;return true;}}
Runner.controls.RowManager=Runner.extend(Runner.emptyFn,{fields:{},rowId:-1,fieldsCount:0,fieldNames:[],constructor:function(rowId){Runner.controls.RowManager.superclass.constructor.call(this,rowId);this.fields={};this.fieldNames=[];this.rowId=rowId;},register:function(control){var controlName=control.fieldName;if(!this.fields[controlName]){this.fields[controlName]=[];this.fieldNames.push(controlName);this.fieldsCount++;}
this.fields[controlName][control.ctrlInd]=control;return true;},getAt:function(fName,controlIndex){if(!fName){var rowControlsArr=[];for(var i=0;i<this.fieldNames.length;i++){for(var j=0;j<this.fields[this.fieldNames[i]].length;j++){var fControl=this.getAt(this.fieldNames[i],j);rowControlsArr.push(fControl);}}
return rowControlsArr;}
if(!this.fields[fName]){return false;}
return this.fields[fName][controlIndex];},unregister:function(fName,controlIndex){if(fName==null){for(var i=0;i<this.fieldsCount;i++){this.unregister(this.fieldNames[i],null);}
return true;}else if(!this.fields[fName]){return false;}else if(controlIndex==null){for(var i=0;i<this.fields[fName].length;i++){this.unregister(fName,i);};for(var i=0;i<this.fieldsCount;i++){if(this.fieldNames[i]==fName){this.fieldNames.splice(i,1);this.fieldsCount--;}}
delete this.fields[fName];return true;}else{if(this.fields[fName][controlIndex].destructor){this.fields[fName][controlIndex].destructor();}else if(this.fields[fName][controlIndex]["destructor"]){this.fields[fName][controlIndex]["destructor"]();}
delete this.fields[fName][controlIndex];return true;}},getMaxFieldIndex:function(fName){if(!this.fields[fName]){return false;}
return this.fields[fName].length;}});Runner.controls.TableManager=Runner.extend(Runner.emptyFn,{rows:{},tName:"",rowsCount:0,rowIds:[],constructor:function(tName){this.tName=tName;this.rows={};this.rowIds=[];},register:function(control){var controlId=control.id;if(!this.rows[controlId]){this.rows[controlId]=new Runner.controls.RowManager(controlId);this.rowIds.push(controlId);this.rowsCount++;}
return this.rows[controlId].register(control);},getAt:function(rowId,fName,controlIndex){if(rowId==null){var tableControlsArr=[];for(var i=0;i<this.rowIds.length;i++){var rowControls=this.rows[this.rowIds[i]].getAt();for(var j=0;j<rowControls.length;j++){tableControlsArr.push(rowControls[j]);}}
return tableControlsArr;}
if(!this.rows[rowId]){return false;}
return this.rows[rowId].getAt(fName,controlIndex);},unregister:function(rowId,fName,controlIndex){if(rowId==null){for(var i=0;i<this.rowsCount;i++){this.rows[this.rowIds[i]].unregister(null,null);}
return true;}else if(!this.rows[rowId]){return false;}else{var rowUnregStat=this.rows[rowId].unregister(fName,controlIndex);if(rowUnregStat&&fName==null){for(var i=0;i<this.rowsCount;i++){if(this.rowIds[i]==rowId){this.rowIds.splice(i,1);this.rowsCount--;}}
delete this.rows[rowId];return true;}else{return rowUnregStat;}}},getMaxFieldIndex:function(rowId,fName){if(!this.rows[rowId]){return false;}
return this.rows[rowId].getMaxFieldIndex(fName);}});Runner.controls.ControlManager=function(){var tables={};var tablesCount=0;var tableNames=[];return{register:function(control){if(!control){return false;}
var controlTable=control.table;if(!tables[controlTable]){tables[controlTable]=new Runner.controls.TableManager(controlTable);tableNames.push(controlTable);tablesCount++;}
return tables[controlTable].register(control);},getAt:function(tName,rowId,fName,controlIndex){if(!tables[tName]){return false;}
controlIndex=controlIndex?controlIndex:0;return tables[tName].getAt(rowId,fName,controlIndex);},unregister:function(tName,rowId,fName,controlIndex){if(!tables[tName]){return false;}
var tUnregStat=tables[tName].unregister(rowId,fName,controlIndex);if(tUnregStat&&rowId==null){for(var i=0;i<tablesCount;i++){if(tableNames[i]==tName){tableNames.splice(i,1);tablesCount--;}}
delete tables[tName];return true;}else{return tUnregStat;}},getMaxFieldIndex:function(tName,rowId,fName){if(!tables[tName]){return false;}
return tables[tName].getMaxFieldIndex(rowId,fName);},resetControlsForTable:function(tName){var cntrls=this.getAt(tName);if(!cntrls){return false;}
for(var i=0;i<cntrls.length;i++){cntrls[i].reset();}
return true;},clearControlsForTable:function(tName){var cntrls=this.getAt(tName);if(!cntrls){return false;}
for(var i=0;i<cntrls.length;i++){cntrls[i].clear();}
return true;}}}();Runner.search.SearchForm=Runner.extend(Runner.emptyFn,{usedSrch:false,id:-1,tName:"",searchType:"panel",conditionRadioTop:null,srchForm:null,ctrlsShowMap:null,constructor:function(cfg){this.ctrlsShowMap={};Runner.apply(this,cfg);Runner.search.SearchForm.superclass.constructor.call(this,cfg);var srchFormId='frmSearch'+this.id;this.srchForm=$('#'+srchFormId);this.conditionRadioTop=$('input:radio[name=srchType]');},addToForm:function(val,id,type){if(typeof val=='undefined'){return false;}
val=(typeof val==='object')?val[0]:val;type=(type?type:'hidden');var formElem=this.srchForm.find('input[name='+id+']');if(formElem.length){formElem.val(val.toString().entityify());}else{var elemHtml='<input type="'+type+'" name="'+id+'" value="'+val.toString().entityify()+'" />';this.srchForm.append(elemHtml);}
return true;},submitSearch:function(){this.addToForm('integrated','a');this.addToForm(this.id,'id');for(var i=0;i<this.conditionRadioTop.length;i++){if(this.conditionRadioTop[i].checked==true){this.addToForm(this.conditionRadioTop[i].value,'criteria');break;}}
var j=1,notVal='';for(var fName in this.ctrlsShowMap){for(var ind in this.ctrlsShowMap[fName]){var fMap=this.ctrlsShowMap[fName][ind];var ctrl1=Runner.controls.ControlManager.getAt(this.tName,ind,fName,fMap[0]);var srchCombo=$('#'+this.getComboId(fName,ind));var comboVal=srchCombo.val();if(ctrl1.isEmpty()&&comboVal.indexOf('Empty')==-1){continue;}
this.addToForm(ctrl1.ctrlType,'type'+j);var ctrl1Val=ctrl1.getStringValue();this.addToForm(ctrl1Val,'value'+j+'1');this.addToForm(fName,'field'+j);if(srchCombo.val().indexOf('NOT')==0){comboVal=comboVal.substr(4);}
this.addToForm(comboVal,'option'+j);var srchCheckBox=$('#'+this.getCheckBoxId(fName,ind));notVal='';if(srchCheckBox.length){notVal=srchCheckBox[0].checked?'on':'';}else{notVal=srchCombo.val().indexOf('NOT')==0?'on':'';}
this.addToForm(notVal,'not'+j);if(srchCombo.val().toLowerCase().indexOf('between')!==-1&&fMap[1]){var ctrl2=Runner.controls.ControlManager.getAt(this.tName,ind,fName,fMap[1]);var ctrl2Val=ctrl2.getStringValue();this.addToForm(ctrl2Val,'value'+j+'2');}
j++;}}
this.usedSrch=true;this.srchForm.submit();},addToShowMap:function(fName,ind,ctrlIndArr){!this.ctrlsShowMap[fName]?this.ctrlsShowMap[fName]={}:'';!this.ctrlsShowMap[fName][ind]?this.ctrlsShowMap[fName][ind]={}:'';this.ctrlsShowMap[fName][ind]=ctrlIndArr;},addRegCtrlsBlock:function(fName,ind,ctrlIndArr){ctrlIndArr?this.addToShowMap(fName,ind,ctrlIndArr):'';},getComboId:function(fName,ind){return"srchOpt_"+ind+"_"+Runner.goodFieldName(fName);},getCheckBoxId:function(fName,ind){return"not_"+ind+"_"+fName;},showAllSubmit:function(){this.addToForm(this.id,'id');this.addToForm('showall','a');this.usedSrch=false;this.srchForm.submit();},returnSubmit:function(){this.addToForm(this.id,'id');this.addToForm('return','a');this.srchForm.submit();},resetCtrls:function(){Runner.controls.ControlManager.resetControlsForTable(this.tName);return false;}});Runner.search.SearchFormWithUI=Runner.extend(Runner.search.SearchForm,{srchOptShowStatus:false,srchWinShowStatus:false,ctrlChooseMenuStatus:false,ctrlTypeComboStatus:false,srchOptDiv:null,srchOptExpander:null,srchWinExpander:null,srchBlock:null,srchCtrlsBlock:null,srchBlockStatus:true,topCritCont:null,ctrlChooseMenuDiv:null,srchPanelHeader:null,panelContainer:null,bottomPanelRound:null,bottomSearchButt:null,hideOptSrc:"images/search/hideOptions.gif",showOptSrc:"images/search/showOptions.gif",showOptText:"Show search options",hideOptText:"Hide search options",showComboText:'Show options',hideComboText:'Hide options',searchTypeCombosArr:null,searchTypeCombosWinArr:null,srchFilterRowArr:null,srchFilterRowWinArr:null,fNamesArr:null,ctrlsShowMap:null,showHideSearchComboButton:null,iframe:null,hider:null,flyDivId:0,recBlockMargChange:false,moveBlockPadding:'padding-left',moveGridDiv:null,constructor:function(cfg){this.searchTypeCombosArr=[];this.searchTypeCombosWinArr=[];this.fNamesArr=[];this.srchFilterRowArr=[];this.srchFilterRowWinArr=[];Runner.search.SearchFormWithUI.superclass.constructor.call(this,cfg);this.srchOptDiv=$("#searchOptions"+this.id);this.srchOptExpander=$("#showOptPanel"+this.id);this.srchWinExpander=$("#showSrchWin"+this.id);var srchBlockId='search_block'+this.id;this.srchBlock=$("#"+srchBlockId);var srchCtrlsBlockId='controlsBlock_'+this.id;this.srchCtrlsBlock=$("#"+srchCtrlsBlockId);var srchCtrlsBlockWinId='controlsBlock_'+this.id+'_win';this.srchCtrlsBlockWin=$("#"+srchCtrlsBlockWinId);var srchPanelHeaderId='searchPanelHeader'+this.id;this.srchPanelHeader=$("#"+srchPanelHeaderId);var showHideSearchComboButtonId='showHideSearchType'+this.id;this.showHideSearchComboButton=$('#'+showHideSearchComboButtonId);var panelContainerId='searchPanelContainer'+this.id;this.panelContainer=$('#'+panelContainerId);var bottomPanelRoundId='searchPanelBottomRound'+this.id;this.bottomPanelRound=$('#'+bottomPanelRoundId);this.moveGridDiv=$("div[@moveforsearch='move"+this.id+"']");if($.browser.msie){if($(document.html).attr('dir').toLowerCase()=='rtl')
this.moveBlockPadding='padding-right';}else{if($("html[@dir=RTL]").length)
this.moveBlockPadding='padding-right';}
var mrgLeft=this.moveGridDiv.css(this.moveBlockPadding);if(mrgLeft=='203px'&&$('#mainmenu_block').length==0){this.recBlockMargChange=true;}
this.addDelegatedEvents();},addDelegatedEvents:function(){var controller=this;this.srchCtrlsBlock.bind('mouseover',function(e){var target=Runner.util.Event.getTarget(e);while(target&&target.id!=controller.srchCtrlsBlock.attr('id')){if(target.id&&target.id.indexOf('filter_')!=-1){$(target).find('img[@class=searchPanelButton]').css('visibility','visible');$(target).removeClass('blockBorder').addClass('blockBorderHovered');break;}else{target=target.parentNode;}}});this.srchCtrlsBlock.bind('mouseout',function(e){var target=Runner.util.Event.getTarget(e);while(target&&target.id!=controller.srchCtrlsBlock.attr('id')){if(target.id&&target.id.indexOf('filter_')!=-1){$(target).find('img[@class=searchPanelButton]').css('visibility','hidden');$(target).removeClass('blockBorderHovered').addClass('blockBorder');break;}else{target=target.parentNode;}}});this.srchCtrlsBlockWin.bind('mouseover',function(e){var target=Runner.util.Event.getTarget(e);while(target.id!=controller.srchCtrlsBlockWin.attr('id')){if(target.nodeName=="TD"){var tr=$(target).parent();tr.find('img[@class=searchPanelButton]').css('visibility','visible');var tds=tr.children();if($(tds[0]).hasClass('srchWinCell')){var lastVisible=tds.length-1;if($(tds[tds.length-1]).children().length===0||$(tds[tds.length-1]).find('*:first-child').css('display')=='none'){lastVisible--;}
$(tds[0]).removeClass('cellBorderCenter').removeClass('cellBorderLeft').addClass('cellBorderCenterHovered').addClass('cellBorderLeftHovered');for(var i=0;i<lastVisible;i++){$(tds[i]).removeClass('cellBorderCenter').removeClass('cellBorderRightHovered').addClass('cellBorderCenterHovered');}
$(tds[lastVisible]).removeClass('cellBorderCenter').removeClass('cellBorderRight').addClass('cellBorderCenterHovered').addClass('cellBorderRightHovered');}
break;}else{target=target.parentNode;}}});this.srchCtrlsBlockWin.bind('mouseout',function(e){var target=Runner.util.Event.getTarget(e);while(target.id!=controller.srchCtrlsBlockWin.attr('id')){if(target.nodeName=="TD"){var tr=$(target).parent();tr.find('img[@class=searchPanelButton]').css('visibility','hidden');var tds=tr.children();if($(tds[0]).hasClass('srchWinCell')){var lastVisible=tds.length-1;if($(tds[tds.length-1]).children().length===0||$(tds[tds.length-1]).find('*:first-child').css('display')=='none'){lastVisible--;}
$(tds[0]).removeClass('cellBorderCenterHovered').removeClass('cellBorderLeftHovered').addClass('cellBorderCenter').addClass('cellBorderLeft');for(var i=0;i<lastVisible;i++){$(tds[i]).removeClass('cellBorderCenterHovered').addClass('cellBorderCenter');}
$(tds[lastVisible]).removeClass('cellBorderCenterHovered').removeClass('cellBorderRightHovered').addClass('cellBorderCenter').addClass('cellBorderRight');}
break;}else{target=target.parentNode;}}});},getComboContId:function(fName,ind,isWin){return"searchType_"+ind+"_"+Runner.goodFieldName(fName)+(isWin?'_win':'');},getFilterDivId:function(fName,ind,isWin){return"filter_"+ind+"_"+Runner.goodFieldName(fName)+(isWin?'_win':'');},recalcWindowDim:function(winObj){if(!this.srchWinShowStatus){return false;}
winObj=(winObj?winObj:$("#fly"+this.flyDivId));var x=winObj.css('left'),y=winObj.css('top');var flyDivDimAndCoorsObj=getFlyDivSizeAndCoors(this.flyDivId,x,y);setFlyDivDimAndCoors(flyDivDimAndCoorsObj,this.flyDivId);return true;},showSearchWin:function(e,id){var headerObj={title:'<span style="color: black;">Search for:&nbsp;</span>',buttons:[{src:'images/search/windowPin.gif',handler:'searchController'+this.id+'.hideSearchWin(); ',alt:'Hide window',title:'Hide window'}],closeButton:false};var cfgObj={headerObj:headerObj,border:{color:$('#controlChooseMenu'+this.id).css('background-color')}};this.showSearchWin=function(e,id){this.hideCtrlChooseMenu();var x=50,y=50;if(Runner.isIE&&e){y=e.y;x=e.x;}else if(e){y=e.clientY;x=e.clientX;}
var oncloseHandlerCode='';this.flyDivId=id||++window.flyid;var divContainer=DisplayFlyDiv("","",this.flyDivId,"",x,y,'search',"",this.flyDivId,oncloseHandlerCode,cfgObj,0);$(divContainer).css('padding-top','10px');$(divContainer).css('background-color',this.panelContainer.css('background-color'));this.srchPanelHeader.appendTo(divContainer);this.srchOptDiv.appendTo(divContainer);this.srchCtrlsBlock.hide();this.moveCtrlsToTable();this.srchCtrlsBlockWin.show();var flyDivDimAndCoorsObj=getFlyDivSizeAndCoors(this.flyDivId,x,y);if(e.w&&e.h){flyDivDimAndCoorsObj.height=e.h;flyDivDimAndCoorsObj.width=e.w;}
setFlyDivDimAndCoors(flyDivDimAndCoorsObj,this.flyDivId);this.showSearchOptions();this.srchWinShowStatus=true;if(this.recBlockMargChange)
this.moveGridDiv.css(this.moveBlockPadding,0);}
this.showSearchWin(e,id);},moveCtrlsToTable:function(){for(var i=0;i<this.srchFilterRowArr.length;i++){var divRowId=this.srchFilterRowArr[i].attr('id');var tableRowId=divRowId+'_win';var tableRow=$('#'+tableRowId);if(this.srchFilterRowArr[i].css('display')!='none'){tableRow.show();}else{tableRow.css('display','none');}
this.moveCtrlsToTableRow(this.srchFilterRowArr[i],tableRow);}},moveCtrlsToTableRow:function(divRow,tableRow){var divCells=divRow.children();var tds=tableRow.children();for(var i=0;i<divCells.length;i++){var divCellChildren=$(divCells[i]).children();divCellChildren.find('script').remove();divCellChildren.appendTo($(tds[i]));if($(divCells[i]).css('display')=='none'){$(tds[i]).hide();}else{$(tds[i]).show();}}
$(tds[1]).html($(divCells[1]).html());},moveCtrlsToDiv:function(){for(var i=0;i<this.srchFilterRowWinArr.length;i++){var tableRowId=this.srchFilterRowWinArr[i].attr('id');var divRowId=tableRowId.substr(0,tableRowId.lastIndexOf('_'));var divRow=$('#'+divRowId);if(this.srchFilterRowWinArr[i].css('display')!='none'){divRow.show();}else{divRow.css('display','none');}
this.moveCtrlsToDivRow(this.srchFilterRowWinArr[i],divRow);}},moveCtrlsToDivRow:function(tableRow,divRow){var divCells=divRow.children();var tds=tableRow.children();for(var i=0;i<tds.length;i++){var tableCellChildren=$(tds[i]).children();tableCellChildren.find('script').remove();tableCellChildren.appendTo($(divCells[i]));if($(tds[i]).css('display')=='none'){$(divCells[i]).hide();}else{$(divCells[i]).show();}}
$(divCells[1]).html($(tds[1]).html());},hideSearchWin:function(id){this.hideCtrlChooseMenu();this.srchOptDiv.prependTo(this.panelContainer);this.corGridDiv();this.srchCtrlsBlockWin.hide();this.moveCtrlsToDiv();this.srchCtrlsBlock.show();this.srchPanelHeader.prependTo($("#searchform"+this.id));RemoveFlyDiv(id||this.flyDivId,true);this.srchWinShowStatus=false;},toggleSearchWin:function(e){this.srchWinShowStatus?this.hideSearchWin():this.showSearchWin(e);this.hideCtrlChooseMenu();},showSearchBlock:function(){this.srchBlock.show();this.srchBlockStatus=true;},hideSearchBlock:function(){this.srchBlock.hide();this.srchBlockStatus=false;},toggleSearchBlock:function(){(this.srchBlockStatus&&!this.srchWinShowStatus)?this.hideSearchBlock():this.showSearchBlock();},corGridDiv:function(){var mrgLeft=this.moveGridDiv.css(this.moveBlockPadding);if(mrgLeft=='auto'||mrgLeft=='0px'){this.recBlockMargChange=true;this.moveGridDiv.css(this.moveBlockPadding,203);}},showSearchOptions:function(){this.corGridDiv();this.srchOptDiv.show();this.bottomPanelRound.css('display','');this.srchOptExpander.css("background-image",'url("'+this.hideOptSrc+'")');this.srchOptExpander.attr('alt',this.hideOptText);this.srchOptExpander.attr('title',this.hideOptText);this.srchOptShowStatus=true;},hideSearchOptions:function(){if(this.recBlockMargChange){this.moveGridDiv.css(this.moveBlockPadding,0);}
this.srchOptDiv.hide();this.bottomPanelRound.css('display','none');this.srchOptExpander.css("background-image",'url("'+this.showOptSrc+'")');this.srchOptExpander.attr('alt',this.showOptText);this.srchOptExpander.attr('title',this.showOptText);this.srchOptShowStatus=false;},toggleSearchOptions:function(){(this.srchOptShowStatus&&!this.srchWinShowStatus)?this.hideSearchOptions():this.showSearchOptions();this.hideCtrlChooseMenu();},showCtrlChooseMenu:function(){if(!this.ctrlChooseMenuDiv){this.ctrlChooseMenuDiv=$("#controlChooseMenu"+this.id);this.ctrlChooseMenuDiv.appendTo(document.body);}
var controller=this;var hideHandler=function(){controller.showCtrlChooseMenu();}
var hideTask=new Runner.util.DelayedTask(hideHandler);controller.ctrlChooseMenuDiv.bind('mouseover',function(e){showTask.cancel();hideTask.delay(50,hideHandler,null,[e]);});var showHandler=function(){controller.hideCtrlChooseMenu();}
var showTask=new Runner.util.DelayedTask(showHandler);controller.ctrlChooseMenuDiv.bind('mouseout',function(e){hideTask.cancel();showTask.delay(50,showHandler,null,[e]);});if(Runner.isIE6){this.iframe=new Runner.util.IEHelper.iframe();this.hider=new Runner.util.IEHelper.selectsHider(this.ctrlChooseMenuDiv[0]);}
this.showCtrlChooseMenu=function(){var posObj=findPos($("#showHideControlChooseMenu"+this.id)[0]);var divT=posObj[1]+posObj[3],divL=posObj[0];this.ctrlChooseMenuDiv.css('top',divT).css('left',divL);this.ctrlChooseMenuDiv.show();this.ctrlChooseMenuDiv[0].offsetWidth<80?this.ctrlChooseMenuDiv.css('width','65px'):'';if(Runner.isIE6&&!this.srchWinShowStatus){this.iframe.reset({l:divL,t:divT,h:this.ctrlChooseMenuDiv[0].offsetHeight,w:this.ctrlChooseMenuDiv[0].offsetWidth});}else if(Runner.isIE6&&this.srchWinShowStatus){this.hider.showSels();this.hider.getSelects();this.hider.hideSels();}
Runner.getZindex(this.ctrlChooseMenuDiv);this.ctrlChooseMenuStatus=true;}
this.showCtrlChooseMenu();},hideCtrlChooseMenu:function(){if(!this.ctrlChooseMenuDiv){this.ctrlChooseMenuDiv=$("#controlChooseMenu"+this.id);this.ctrlChooseMenuDiv.appendTo(document.body);}
this.ctrlChooseMenuDiv.hide();this.ctrlChooseMenuStatus=false;if(Runner.isIE6&&!this.srchWinShowStatus&&this.iframe){this.iframe.hide();}else if(Runner.isIE6&&this.srchWinShowStatus&&this.iframe){this.hider.showSels();}},toggleCtrlChooseMenu:function(){this.ctrlChooseMenuStatus?this.hideCtrlChooseMenu():this.showCtrlChooseMenu();},showCtrlTypeCombo:function(){for(var i=0;i<this.searchTypeCombosArr.length;i++){this.searchTypeCombosArr[i].show();this.searchTypeCombosArr[i].find('select').show();}
for(var i=0;i<this.searchTypeCombosWinArr.length;i++){this.searchTypeCombosWinArr[i].show();this.searchTypeCombosWinArr[i].find('select').show();}
this.showHideSearchComboButton.html(this.hideComboText);this.showHideSearchComboButton.attr('title',this.hideComboText);this.ctrlTypeComboStatus=true;},hideCtrlTypeCombo:function(){for(var i=0;i<this.searchTypeCombosArr.length;i++){this.searchTypeCombosArr[i].hide();this.searchTypeCombosArr[i].find('select').hide();}
for(var i=0;i<this.searchTypeCombosWinArr.length;i++){this.searchTypeCombosWinArr[i].hide();this.searchTypeCombosWinArr[i].find('select').hide();}
this.showHideSearchComboButton.html(this.showComboText);this.showHideSearchComboButton.attr('title',this.showComboText);this.ctrlTypeComboStatus=false;},toggleCtrlTypeCombo:function(){this.ctrlTypeComboStatus?this.hideCtrlTypeCombo():this.showCtrlTypeCombo();},toggleCrit:function(ctrlsCount){var topCritContId='srchCritTop'+this.id;this.topCritCont=$('#'+topCritContId);var bottomSearchButtId='bottomSearchButt'+this.id;this.bottomSearchButt=$('#'+bottomSearchButtId);this.toggleCrit=function(ctrlsCount){ctrlsCount>1?this.topCritCont.show():this.topCritCont.hide();ctrlsCount>0?this.bottomSearchButt.show():this.bottomSearchButt.hide();}
this.toggleCrit(ctrlsCount);}});Runner.search.SearchController=Runner.extend(Runner.search.SearchFormWithUI,{smplSrchBox:null,simpleSrchTypeCombo:null,simpleSrchFieldsCombo:null,panelStateExpires:'',ajaxSearchUrl:"",styleDispNoneText:'display: none;',shortTName:"",constructor:function(cfg){Runner.search.SearchController.superclass.constructor.call(this,cfg);this.ajaxSearchUrl=this.shortTName+'_search.php';this.smplSrchBox=$('#ctlSearchFor'+this.id);this.simpleSrchTypeCombo=$('#simpleSrchTypeCombo'+this.id);this.simpleSrchFieldsCombo=$('#simpleSrchFieldsCombo'+this.id);var oldOnUnload=window.onunload;var controller=this;window.onunload=function(){if(oldOnUnload){oldOnUnload();}
controller.rememberPanelState();}},getLastAddedInd:function(filterName){if(!this.ctrlsShowMap[filterName]){return false;}
var maxInd=0,beforeMaxInd=false,i=0;for(var ind in this.ctrlsShowMap[filterName]){ind=parseInt(ind);if(maxInd<ind){beforeMaxInd=maxInd;maxInd=ind;}
if(i===0){beforeMaxInd=maxInd;}
i++;}
return beforeMaxInd;},getLastAdded:function(filterName){var beforeMaxInd=this.getLastAddedInd(filterName);if(!beforeMaxInd){return false;}
var filterObj=$('#'+this.getFilterDivId(filterName,beforeMaxInd,this.srchWinShowStatus));if(filterObj.length){return filterObj;}else{return false;}},addCtrlsHtml:function(fName,ind,blockHTML){this.addPanelHtml(fName,ind,blockHTML);this.addTableHtml(fName,ind);var rowCont=$('#'+this.getFilterDivId(fName,ind,this.srchWinShowStatus))
var cells=rowCont.children();$(cells[0]).html(blockHTML.delButt);$(cells[2]).html(blockHTML.comboHtml);$(cells[3]).html(blockHTML.control1);$(cells[4]).html(blockHTML.control2);eval(blockHTML.jsCode);},addTableHtml:function(fName,ind){var newSrchCtrlContId=this.getFilterDivId(fName,ind,true);var filterRowHtml=this.createTableRow(newSrchCtrlContId,'winRow',this.styleDispNoneText,'');this.srchCtrlsBlockWin.append(filterRowHtml);var newSrchCtrlCont=$("#"+newSrchCtrlContId);newSrchCtrlCont.append(this.createTableCell('','srchWinCell','',''));var fNameCellHtml=this.createTableCell('','srchWinCell','',fName+':&nbsp;');newSrchCtrlCont.append(fNameCellHtml);var comboHtml=this.createTableCell(this.getComboContId(fName,ind,true),'srchWinCell',(this.ctrlTypeComboStatus?'':this.styleDispNoneText),'');newSrchCtrlCont.append(comboHtml);newSrchCtrlCont.append(this.createTableCell('','srchWinCell','',''));newSrchCtrlCont.append(this.createTableCell('','srchWinCell','',''));return newSrchCtrlCont;},addPanelHtml:function(fName,ind,blockHTML){var newSrchCtrlContId=this.getFilterDivId(fName,ind);var filterDivHtml=this.createDivCont(newSrchCtrlContId,'srchPanelRow blockBorder',this.styleDispNoneText,'');this.srchCtrlsBlock.append(filterDivHtml);var newSrchCtrlCont=$("#"+newSrchCtrlContId);newSrchCtrlCont.append(this.createDivCont('','srchPanelCell','',''));var fNameDivHtml=this.createDivCont('','srchPanelCell','',blockHTML.fLabel+':&nbsp;');newSrchCtrlCont.append(fNameDivHtml);var comboHtml=this.createDivCont(this.getComboContId(fName,ind),'srchPanelCell srchPanelCell2',(this.ctrlTypeComboStatus?'':this.styleDispNoneText),'');newSrchCtrlCont.append(comboHtml);newSrchCtrlCont.append(this.createDivCont('','srchPanelCell srchPanelCell2','',''));newSrchCtrlCont.append(this.createDivCont('','srchPanelCell srchPanelCell2','',''));return newSrchCtrlCont;},addRegCtrlsBlock:function(fName,ind,ctrlIndArr,blockHTML){Runner.search.SearchController.superclass.addRegCtrlsBlock.call(this,fName,ind,ctrlIndArr);blockHTML?this.addCtrlsHtml(fName,ind,blockHTML):"";var ctrl=Runner.controls.ControlManager.getAt(this.tName,ind,fName);if(!ctrl.hidden){this.setDependences(ctrl);}
this.searchTypeCombosArr.push($("#"+this.getComboContId(fName,ind)));this.searchTypeCombosWinArr.push($("#"+this.getComboContId(fName,ind,true)));this.srchFilterRowArr.push($("#"+this.getFilterDivId(fName,ind)));this.srchFilterRowWinArr.push($("#"+this.getFilterDivId(fName,ind,true)));this.toggleCrit(this.getVisibleBlocksCount());},createDivCont:function(id,cssClass,style,innerHtml){return'<div class="'+cssClass+'" id="'+id+'" style="'+style+'">'+innerHtml+'</div>';},createTableRow:function(id,cssClass,style,innerHtml){return'<tr class="'+cssClass+'" id="'+id+'" style="'+style+'">'+innerHtml+'</tr>';},createTableCell:function(id,cssClass,style,innerHtml){return'<td class="'+cssClass+'" id="'+id+'" style="'+style+'">'+innerHtml+'</td>';},putCachedBlock:function(filterName,cachedInd,parentFieldName){var cachedRow=$("#"+this.getFilterDivId(filterName,cachedInd,this.srchWinShowStatus));var lastAdded=this.getLastAdded(filterName);if(parentFieldName&&this.getLastAdded(parentFieldName)){cachedRow.insertAfter(this.getLastAdded(parentFieldName));}else if(lastAdded){cachedRow.insertBefore(lastAdded);}else{if(this.srchWinShowStatus){this.srchCtrlsBlockWin.prepend(cachedRow);}else{this.srchCtrlsBlock.prepend(cachedRow);}}
cachedRow.show();},createLoadingBox:function(filterName){var loadingTxt='&nbsp;&nbsp;'+filterName+':&nbsp;loading&nbsp;...&nbsp;';if(!this.srchWinShowStatus){var loadDiv=document.createElement('DIV');$(loadDiv).addClass('blockBorderHovered').html(loadingTxt);return loadDiv;}else{var loadTr=document.createElement('TR');var loadTd=document.createElement('TD');$(loadTd).attr('colspan','4').addClass('cellBorderRightHovered').addClass('cellBorderLeftHovered').addClass('cellBorderCenterHovered').html(loadingTxt);$(loadTr).addClass('winRow').append(loadTd);return loadTr;}},putLoadingBox:function(loadBox,filterName){var lastAdded=this.getLastAdded(filterName);if(lastAdded){$(loadBox).insertBefore(lastAdded);}else{if(this.srchWinShowStatus){this.srchCtrlsBlockWin.append($(loadBox));}else{this.srchCtrlsBlock.append($(loadBox));}}},setDependences:function(ctrl,triggerReload){if(!ctrl.isLookupWizard){return false;}
if(!ctrl.parentFieldName||!this.ctrlsShowMap[ctrl.parentFieldName]){ctrl.reload();return false;}
var parentInd=this.getLastAddedInd(ctrl.parentFieldName);if(!this.ctrlsShowMap[ctrl.parentFieldName][parentInd]){return false;}
var parentCtrl=Runner.controls.ControlManager.getAt(this.tName,parentInd,ctrl.parentFieldName,this.ctrlsShowMap[ctrl.parentFieldName][parentInd][0]);if(parentCtrl.showStatus){ctrl.setParentCtrl(parentCtrl);parentCtrl.addDependentCtrls([ctrl]);if(triggerReload===true){parentCtrl.fireEvent('change');}}else{ctrl.reload();}
return true;},getShownFilterNames:function(){var fNamesArr=[];for(var fName in this.ctrlsShowMap){var cachedInd=0;for(var ind in this.ctrlsShowMap[fName]){ind=parseInt(ind);if($("#"+this.getFilterDivId(fName,ind,this.srchWinShowStatus)).css('display')!='none'){fNamesArr.push(fName);}}}
return fNamesArr;},showCached:function(filterName){if(!this.ctrlsShowMap[filterName]){return false;}
var cachedInd=0;for(var ind in this.ctrlsShowMap[filterName]){ind=parseInt(ind);cachedInd=cachedInd<ind?ind:cachedInd;}
if($("#"+this.getFilterDivId(filterName,cachedInd,this.srchWinShowStatus)).css('display')!='none'){return false;}
var cachedCtrlIndArr=this.ctrlsShowMap[filterName][cachedInd];var objIndForCM,parentFieldName,parentCtrl=null,parentInd=false,ctrl1;for(var i=0;i<cachedCtrlIndArr.length;i++){objIndForCM=cachedCtrlIndArr[i];var ctrlFromCache=Runner.controls.ControlManager.getAt(this.tName,cachedInd,filterName,objIndForCM);if(i===0){ctrl1=ctrlFromCache;ctrl1.show();}
parentFieldName=ctrlFromCache.parentFieldName;this.setDependences(ctrlFromCache,true);ctrlFromCache.spanContElem.find('script').remove();}
this.putCachedBlock(filterName,cachedInd,parentFieldName);if(this.ctrlTypeComboStatus){$("#"+this.getComboContId(filterName,cachedInd)).show();}
if(!this.srchWinShowStatus){ctrl1.setFocus();}
return true;},addFilter:function(filterName){var isShown=this.showCached(filterName);if(!isShown){var loadBox=this.createLoadingBox(filterName);this.putLoadingBox(loadBox,filterName);}else{this.ctrlTypeComboStatus?this.showCtrlTypeCombo():this.hideCtrlTypeCombo();}
var ajaxParams={searchControllerId:this.id,rndval:Math.random(),mode:"inlineLoadCtrl",ctrlField:myEncode(filterName),id:flyid};flyid++;var controller=this;$.getJSON(this.ajaxSearchUrl,ajaxParams,function(ctrlJSON,queryStatus){controller.addRegCtrlsBlock(filterName,ctrlJSON.divInd,(ctrlJSON.control2?[0,1]:[0]),ctrlJSON);if(!isShown){controller.showCached(filterName);$(loadBox).remove();controller.toggleCrit(controller.getVisibleBlocksCount());controller.ctrlTypeComboStatus?controller.showCtrlTypeCombo():controller.hideCtrlTypeCombo();}});},delCtrl:function(fName,ind){var objIndForCM;for(var i=0;i<this.ctrlsShowMap[fName][ind].length;i++){objIndForCM=this.ctrlsShowMap[fName][ind][i];if(objIndForCM.isLookupWizard){objIndForCM.clearChildrenLinks(true);}
Runner.controls.ControlManager.unregister(this.tName,this.id,fName,objIndForCM);}
this.removeComboById(this.getComboContId(fName,ind));this.removeFilterById(this.getFilterDivId(fName,ind));if(this.srchWinShowStatus){this.recalcWindowDim();}
this.toggleCrit(this.getVisibleBlocksCount());delete this.ctrlsShowMap[fName][ind];},removeFilterById:function(id){var isUseWinId=(id.lastIndexOf('_win')!=-1);id=(isUseWinId?id.substr(0,id.lastIndexOf('_')):id);var elemInd=this.srchFilterRowArr.getIndexOfElem(id,function(val,elem){return elem.attr('id')==val;});if(elemInd!==-1){this.srchFilterRowArr[elemInd].remove();this.srchFilterRowArr.splice(elemInd,1);}
id+='_win';var elemInd=this.srchFilterRowWinArr.getIndexOfElem(id,function(val,elem){return elem.attr('id')==val;});if(elemInd!==-1){this.srchFilterRowWinArr[elemInd].remove();this.srchFilterRowWinArr.splice(elemInd,1);}},removeComboById:function(id){var isUseWinId=(id.lastIndexOf('_win')!=-1);id=(isUseWinId?id.substr(0,id.lastIndexOf('_')):id);var elemInd=this.searchTypeCombosArr.getIndexOfElem(id,function(val,elem){return elem.attr('id')==val;});if(elemInd!==-1){this.searchTypeCombosArr.splice(elemInd,1);}
id+='_win';var elemInd=this.searchTypeCombosWinArr.getIndexOfElem(id,function(val,elem){return elem.attr('id')==val;});if(elemInd!==-1){this.searchTypeCombosWinArr.splice(elemInd,1);}},getVisibleBlocksCount:function(){var visCount=0;var rowArr=(this.srchWinShowStatus?this.srchFilterRowWinArr:this.srchFilterRowArr);for(var i=0;i<rowArr.length;i++){if(rowArr[i].css('display')!='none'){visCount++;}}
return visCount;},submitSearch:function(){this.rememberPanelState();if(!this.usedSrch&&!this.smplUsed){this.smplSrchBox.val('');}
this.addToForm(this.smplSrchBox.val(),'ctlSearchFor');this.addToForm(this.simpleSrchFieldsCombo.val(),'simpleSrchFieldsComboOpt');var simpleSrchTypeComboVal=this.simpleSrchTypeCombo.val();if(simpleSrchTypeComboVal&&simpleSrchTypeComboVal.indexOf('NOT')==0){simpleSrchTypeComboVal=simpleSrchTypeComboVal.substr(4);this.addToForm('on','simpleSrchTypeComboNot');}else{this.addToForm('','simpleSrchTypeComboNot');}
this.addToForm(simpleSrchTypeComboVal,'simpleSrchTypeComboOpt');Runner.search.SearchController.superclass.submitSearch.call(this);},resetCtrls:function(){var objIndForCM;for(var fName in this.ctrlsShowMap){for(var ind in this.ctrlsShowMap[fName]){for(var i=0;i<this.ctrlsShowMap[fName][ind].length;i++){objIndForCM=this.ctrlsShowMap[fName][ind][i];var ctrl=Runner.controls.ControlManager.getAt(this.tName,this.id,fName,objIndForCM);ctrl.reset();}}}
return false;},rememberPanelState:function(){var cutFrom=document.location['pathname'].lastIndexOf('/',1);var cookieRoot=document.location['pathname'].substr(0,(cutFrom+1));var panelStateObj={srchPanelOpen:this.srchOptShowStatus,srchCtrlComboOpen:this.ctrlTypeComboStatus,srchWinOpen:this.srchWinShowStatus,openFilters:[]};if(this.srchWinShowStatus){var win=$("#fly"+this.flyDivId);panelStateObj.winState={x:win.css('left'),clientX:win.css('left'),clientY:win.css('top'),y:win.css('top'),h:win.css('height'),w:win.css('width')};}
if(!this.usedSrch){panelStateObj.openFilters=this.getShownFilterNames();}
var panelStateString=JSON.stringify(panelStateObj);set_cookie('panelState_'+this.shortTName+'_'+this.id,panelStateString,this.panelStateExpires,cookieRoot,'','');},remindPanelState:function(){var panelStateString=get_cookie('panelState_'+this.shortTName+'_'+this.id);if(!panelStateString){return;}
var panelStateObj=JSON.parse(panelStateString);if(panelStateObj.srchWinOpen){this.hideSearchOptions();this.showSearchWin(panelStateObj.winState);}else if(panelStateObj.srchPanelOpen){this.showSearchOptions();}
if(panelStateObj.srchCtrlComboOpen){this.showCtrlTypeCombo();}else{this.hideCtrlTypeCombo();}
if(!this.usedSrch){for(var i=0;i<this.panelSearchFields.length;i++){var elemIndex=panelStateObj.openFilters.getIndexOfElem(this.panelSearchFields[i]);if(elemIndex!=-1){panelStateObj.openFilters.splice(elemIndex,1);}}
for(var i=0;i<panelStateObj.openFilters.length;i++){this.addFilter(panelStateObj.openFilters[i]);}}}});Runner.controls.Control=Runner.extend(Runner.Event,{fieldName:"",goodFieldName:"",shortTableName:"",id:"",css:"",style:"",valContId:"",valueElem:null,spanContId:"",spanContElem:null,errContId:"",errContainer:null,validationArr:[],defaultValue:null,isResetHappend:false,table:"",regExp:null,inputType:"",ctrlType:"",showStatus:true,ctrlInd:-1,isSetFocus:false,hidden:false,mode:'',isInvalid:false,constructor:function(cfg){this.validationArr=new Array();Runner.apply(this,cfg);Runner.controls.Control.superclass.constructor.call(this,cfg);this.valContId="value"+(cfg.ctrlInd||"")+"_"+this.goodFieldName+"_"+this.id;this.valueElem=(this.valueElem==null)?$("#"+this.valContId):this.valueElem;this.spanContId="edit"+this.id+"_"+this.goodFieldName+"_"+cfg.ctrlInd;this.spanContElem=$("#"+this.spanContId);this.errContId="errorCont"+cfg.ctrlInd+"_"+this.valContId;if(cfg.disabled===true||cfg.disabled==="true"){this.setDisabled();}
if(cfg.hidden===true||cfg.hidden==="true"){this.hide();}
this.ccs?valueElem.addclass(this.css):'';this.addStyle(this.style);this.defaultValue=this.getValue();if(this.valueElem.attr&&this.valueElem.attr("type")){this.inputType=this.valueElem.attr("type");}
this.addEvent(["click"]);if(cfg.stopEventInit!==true){this.elemsForEvent=[this.valueElem.get(0)];this.addEvent(["blur"]);this.init();}
Runner.controls.ControlManager.register(this);validation.registerCustomValidation(this);},addStyle:function(styleToAdd){if(!styleToAdd){return false;}
var stylesArr=styleToAdd.split(';');for(var i=0;i<stylesArr.length;i++){var style=stylesArr[i].split(":");style[0]=style[0].toString().trim();if(!style[0]){continue;}
style[1]=style[1].toString().trim();this.valueElem.css(style[0],style[1]);}
return true;},validate:function(valArr){var vRes=validation.validate(valArr||this.validationArr,this);if(valArr||this.validationArr.length){if(!vRes.result){this.markInvalid(vRes.messageArr);}else{this.clearInvalid();}}
return vRes;},removeValidation:function(vType){for(var i=0;i<this.validationArr.length;i++){if(this.validationArr[i]==vType){this.validationArr.splice(i,1);return true;}}
return false;},addValidation:function(vType){if(!this.isSetValidation(vType)){this.validationArr[this.validationArr.length]=vType;}},isSetValidation:function(vType){if(!validation[vType]){return false;}
for(var i=0;i<this.validationArr.length;i++){if(this.validationArr[i]==vType){return true;}}
return false;},validateAs:function(vType){return validation[vType](this.getValue());},initErrorCont:function(){this.errContainer=document.createElement('div');this.errContainer=$(this.errContainer);this.errContainer.attr('id',this.errContId);this.errContainer.addClass('errorText');this.errContainer.css('display',"none");this.errContainer.appendTo(this.spanContElem);this.initErrorCont=Runner.emptyFn;},markInvalid:function(messArr){this.initErrorCont();this.markInvalid=function(messArr){var divInnerHtml="";this.errContainer.show();for(var i=0;i<messArr.length;i++){divInnerHtml+=messArr[i]+"</br>";}
this.errContainer.html(divInnerHtml);this.isInvalid=true;}
this.markInvalid(messArr);},clearInvalid:function(){this.initErrorCont();this.clearInvalid=function(){this.errContainer.hide();this.errContainer.empty();this.isInvalid=false;}
this.clearInvalid();},invalid:function(){return this.isInvalid;},reset:function()
{this.isResetHappend=true;this.setValue(this.defaultValue);this.clearInvalid();this.isResetHappend=false;return true;},clear:function(){this.setValue('');this.clearInvalid();return true;},hide:function(){this.spanContElem.css("display","none");this.showStatus=false;},show:function(){this.spanContElem.css("display","");this.showStatus=true;},toggleHide:function(){if(this.showStatus){this.hide();}else{this.show();}},getValue:function(){if(this.valueElem.val){return this.valueElem.val();}else{return false;}},getStringValue:function(){return this.getValue();},setValue:function(val,triggerEvent){if(this.valueElem.val){this.valueElem.val(val);if(triggerEvent===true){this.fireEvent("change");}}else{return false;}},setDisabled:function(){if(this.valueElem.get(0)){this.valueElem.get(0).disabled=true;return true;}else{return false;}},setEnabled:function(){if(this.valueElem.get(0)){this.valueElem.get(0).disabled=false;return true;}else{return false;}},getControlType:function(){return this.inputType;},setFocus:function(triggerEvent){var cType=this.getControlType();if(cType!=""&&(cType=='text'||cType=='password'||cType=='file'||cType=='textarea')){if(this.valueElem.get(0).disabled==true||!this.showStatus||this.valueElem.css('display')=='none'||this.valueElem.css('visibility')=='hidden'){return false;}
try{this.valueElem.get(0).focus();}catch(err){}
if(triggerEvent===true){this.fireEvent("focus");}
this.isSetFocus=true;return true;}else{this.isSetFocus=false;return false;}},isEmpty:function(){return this.getValue().toString()=="";},"blur":function(e){this.stopEvent(e);this.isSetFocus=false;var len=this.validationArr.length;if(this.validationArr[len-1]=='IsRequired'){var valArr=this.validationArr.slice(0,len-1)}else{var valArr=this.validationArr;}
return this.validate(valArr);},"click":function(e){this.isSetFocus=true;},removeCSS:function(className){this.valueElem.removeClass(className);},addCSS:function(className){this.valueElem.addClass(className);},getAttr:function(attrName){return this.valueElem.attr(attrName);},getDispElem:function(){return this.valueElem;},getForSubmit:function(){return[this.valueElem.clone()];}});Runner.controls.TextArea=Runner.extend(Runner.controls.Control,{constructor:function(cfg){this.addEvent(["change","keyup"]);Runner.controls.TextArea.superclass.constructor.call(this,cfg);this.inputType="textarea";},getForSubmit:function(){return[this.valueElem.clone().val(this.getValue())]}});Runner.controls.TextField=Runner.extend(Runner.controls.Control,{constructor:function(cfg){this.addEvent(["change","keyup"]);Runner.controls.TextField.superclass.constructor.call(this,cfg);}});Runner.controls.TimeField=Runner.extend(Runner.controls.Control,{typeHiddId:"",typeHiddElem:null,constructor:function(cfg){Runner.controls.TimeField.superclass.constructor.call(this,cfg);this.typeHiddId="type_"+this.goodFieldName+"_"+this.id;this.typeHiddElem=$("#"+this.typeHiddId);this.imgTime=$("#trigger-test-"+this.valContId);if(this.imgTime.length&&!Runner.isIE){this.imgTime.css('visibility','visible');}
if(cfg.disabled===true||cfg.disabled==="true"){this.setDisabled();}
this.addEvent(["change"]);this.init();},addValidation:function(type){if(type!="isRequired"){return false;}
Runner.controls.TimeField.superclass.addValidation.call(this,type);},getForSubmit:function(){return[this.valueElem.clone(),this.typeHiddElem.clone()];},setDisabled:function()
{if(this.valueElem.get(0)&&this.imgTime)
{this.valueElem.get(0).disabled=true;this.imgTime.css('visibility','hidden');return true;}else{return false;}},setEnabled:function()
{if(this.valueElem.get(0))
{this.valueElem.get(0).disabled=false;if(!Runner.isIE){this.imgTime.css('visibility','visible');}
return true;}else{return false;}},"change":function(e)
{return this.validate().result;}});Runner.controls.RTEField=Runner.extend(Runner.controls.Control,{iframeElemId:"",iframeElem:null,constructor:function(cfg){cfg.stopEventInit=true;Runner.controls.RTEField.superclass.constructor.call(this,cfg);this.inputType="RTE";this.iframeElemId=this.valContId;this.valContId="";if(cfg.disabled==true||cfg.disabled=="true"){this.setDisabled();}},useRTE:false,addValidation:function(type)
{if(type!="isRequired")
return false;Runner.controls.RTEField.superclass.addValidation.call(this,type);},getForSubmit:function()
{var clElem=$('<input type="hidden" name="'+this.iframeElemId+'">').clone();$(clElem).val(this.getValue());return[clElem];},setDisabled:function()
{if(this.iframeElem){var val=this.getValue();this.iframeElem.css('display','none');this.spanContElem.prepend('<div id="disabledRTE'+this.fieldName+'_'+this.id+'">'+val+'</div>')
return true;}else{return false;}},setEnabled:function()
{if(this.iframeElem){$("#disabledRTE"+this.fieldName+'_'+this.id).remove();this.iframeElem.css('display','block');return true;}else{return false;}}});Runner.controls.RTEInnova=Runner.extend(Runner.controls.RTEField,{constructor:function(cfg)
{Runner.controls.RTEInnova.superclass.constructor.call(this,cfg);this.useRTE=cfg.useRTE?cfg.useRTE:false;this.iframeElem=$('#'+this.iframeElemId);if(this.useRTE=="INNOVA")
this.innerIframeId='idContentoEdit'+this.goodFieldName+'_'+this.id;},getValue:function()
{var val;if(this.iframeElem)
{if(this.useRTE=='RTE')
val=this.iframeElem.contents().find('#'+this.iframeElemId).contents().find('body').html();else
val=this.iframeElem.contents().find('#'+this.innerIframeId).contents().find('body').html();if(val)
val=val.trim();if(val=='<br>')
val='';return val;}
else
return false;},setValue:function(val)
{if(this.useRTE=='RTE')
this.iframeElem.contents().find('#'+this.iframeElemId).contents().find('body').html(val);else
this.iframeElem.contents().find('#'+this.innerIframeId).contents().find('body').html(val);}});Runner.controls.RTECK=Runner.extend(Runner.controls.RTEField,{constructor:function(cfg)
{Runner.controls.RTECK.superclass.constructor.call(this,cfg);this.iframeElem=$('#'+this.iframeElemId+'___Frame');},getValue:function()
{var val;if(this.iframeElem)
{var ckval=CKeditorAPI.GetInstance(this.iframeElemId);if(ckval!=undefined)
val=ckval.GetXHTML();else
val=$(elem).val();return val;}
else
return false;},setValue:function(val)
{this.iframeElem.contents().find('#xEditingArea').find('iframe').contents().find('body').text(val);}});Runner.controls.FileControl=Runner.extend(Runner.controls.Control,{radioElemsName:"",radioElems:null,constructor:function(cfg){this.radioElems={};cfg.stopEventInit=true;Runner.controls.FileControl.superclass.constructor.call(this,cfg);this.radioElemsName="type_"+this.goodFieldName+"_"+this.id;if($('#'+this.radioElemsName).length){this.getChekedRadio=function(){return false;}}
this.getRadioControls();this.events=["change"];delete this["blur"];this.elemsForEvent=[this.valueElem.get(0)];this.init();},"blur":Runner.emptyFn,"change":function(e){this.stopEvent(e);this.changeRadio("updateRadio");return this.validate();},changeRadio:function(radioToCheck){for(var radio in this.radioElems){if(radio==radioToCheck&&this.radioElems[radio]!=false){this.radioElems[radio].elem.get(0).checked=true;this.radioElems[radio].cheked=true;}else if(radio==radioToCheck&&this.radioElems[radio]==false){return false;}else if(this.radioElems[radio]!=false){this.radioElems[radio].elem.get(0).checked=false;this.radioElems[radio].cheked=false;}}
return true;},getRadioControls:function(){var keepRadio=$('#'+this.radioElemsName+'_keep');var ctrl=this;keepRadio.bind('click',function(e){ctrl.changeRadio('keepRadio');});var deleteRadio=$('#'+this.radioElemsName+'_delete');deleteRadio.bind('click',function(e){ctrl.changeRadio('deleteRadio');});var updateRadio=$('#'+this.radioElemsName+'_update');updateRadio.bind('click',function(e){ctrl.changeRadio('updateRadio');});this.radioElems["keepRadio"]=keepRadio.length?{elem:keepRadio,cheked:true}:false;this.radioElems["deleteRadio"]=deleteRadio.length?{elem:deleteRadio,cheked:false}:false;this.radioElems["updateRadio"]=updateRadio.length?{elem:updateRadio,cheked:false}:false;return true;},getChekedRadio:function(){for(var radio in this.radioElems){if(this.radioElems[radio]!=false&&this.radioElems[radio].cheked===true){return radio;}}
return false;},getForSubmit:function(){var radio=this.getChekedRadio();var cloneArr=[];if(radio){var radioClone=document.createElement('input');$(radioClone).attr('type','hidden');$(radioClone).attr('id',this.radioElems[radio].elem.attr('id'));$(radioClone).attr('name',this.radioElems[radio].elem.attr('name'));$(radioClone).val(this.radioElems[radio].elem.val());cloneArr.push($(radioClone));}else if($('#'+this.radioElemsName).length){cloneArr.push($('#'+this.radioElemsName));}
var realFile=this.valueElem;var clone=this.valueElem.clone(true);clone.insertAfter(realFile);cloneArr.push(realFile);return cloneArr;}});Runner.controls.ImageField=Runner.extend(Runner.controls.FileControl,{constructor:function(cfg){Runner.controls.ImageField.superclass.constructor.call(this,cfg);}});Runner.controls.FileField=Runner.extend(Runner.controls.FileControl,{addTimeStamp:false,fileNameElemId:"",fileNameElem:null,fileHiddElemId:"",fileHiddElem:null,constructor:function(cfg){cfg.stopEventInit=true;Runner.controls.FileField.superclass.constructor.call(this,cfg);this.fileNameElemId="filename_"+this.goodFieldName+"_"+this.id;this.fileNameElem=$("#"+this.fileNameElemId).length?$("#"+this.fileNameElemId):null;this.fileHiddElemId="filenameHidden_"+this.goodFieldName+"_"+this.id;this.fileHiddElem=$("#"+this.fileHiddElemId).length?$("#"+this.fileHiddElemId):null;this.addTimeStamp=cfg.addTimeStamp?cfg.addTimeStamp:false;for(radio in this.radioElems){if(this.radioElems[radio]){var objScope=this;this.radioElems[radio].elem.bind('click',function(e){var radioTypeStartFrom=this.id.lastIndexOf('_');var radioTypeName=this.id.substring(radioTypeStartFrom+1)+'Radio';objScope.changeControlsStyles(radioTypeName);});}}},addValidation:function(type){if(type!="isRequired"){return false;}
Runner.controls.FileField.superclass.addValidation.call(this,type);},getFileNameFromPath:function(path){var wpos=path.lastIndexOf('\\');var upos=path.lastIndexOf('/');var pos=wpos;if(upos>wpos)
pos=upos;return path.substr(pos+1);},setValue:function(val,triggerEvent){var valWithStamp="",fileName="";if(this.fileNameElem!=null||this.addTimeStamp){fileName=this.getFileNameFromPath(this.valueElem.val());}
if(this.addTimeStamp){var valWithStamp=addTimestamp(fileName);}
if(this.fileNameElem!=null){this.fileNameElem.val(valWithStamp||fileName);}
if(triggerEvent===true){this.fireEvent("change");}},"change":function(e){this.stopEvent(e);this.changeRadio("updateRadio");var vRes=this.validate();if(vRes.result){var vl=this.getValue();this.setValue(vl,false);}
return vRes.result;},changeRadio:function(radioToCheck){this.changeControlsStyles(radioToCheck);Runner.controls.FileField.superclass.changeRadio.call(this,radioToCheck);},changeControlsStyles:function(radioToCheck){if(!this.radioElems[radioToCheck]){return false;}
if(this.fileNameElem==null){return false;}
if(radioToCheck=="deleteRadio"){this.fileNameElem.css('backgroundColor','gainsboro');this.fileNameElem[0].disabled=true;return true;}else if(radioToCheck=="updateRadio"||radioToCheck=="keepRadio"){this.fileNameElem.css('backgroundColor','white');this.fileNameElem[0].disabled=false;return true;}else{return false;}},isEmpty:function(){if(this.fileHiddElem&&this.fileHiddElem.val()!=""){return this.radioElems["deleteRadio"].cheked===false;}else{return this.getValue.toString!=""&&this.radioElems["updateRadio"].cheked===true;}},getFileName:function(){if(this.fileHiddElem){return this.fileHiddElem.val();}else{return false;}},setFileName:function(fileName){if(this.fileHiddElem){this.fileHiddElem.val(fileName);return true;}else{return false;}},getForSubmit:function(){var cloneArr=Runner.controls.ImageField.superclass.getForSubmit.call(this);if(this.fileNameElem){cloneArr.push(this.fileNameElem.clone());}
if(this.fileHiddElem){cloneArr.push(this.fileHiddElem.clone());}
return cloneArr;}});Runner.controls.DateField=Runner.extend(Runner.controls.Control,{datePickerHiddId:"",datePickerHiddElem:null,imgCal:null,useDatePicker:false,dateFormatHiddId:"",dateFormat:"",showTime:false,dateFormatHiddElem:null,constructor:function(cfg){Runner.controls.DateField.superclass.constructor.call(this,cfg);this.useDatePicker=cfg.useDatePicker?cfg.useDatePicker:false;this.dateFormat=cfg.dateFormat?cfg.dateFormat:"";this.showTime=cfg.showTime?cfg.showTime:false;if(this.useDatePicker){this.datePickerHiddId="tsvalue"+(cfg.ctrlInd||"")+"_"+this.goodFieldName+"_"+this.id;this.datePickerHiddElem=$("#"+this.datePickerHiddId);}
this.dateFormatHiddId="type"+(cfg.ctrlInd||"")+"_"+this.goodFieldName+"_"+this.id;this.dateFormatHiddElem=$("#"+this.dateFormatHiddId);if(this.useDatePicker)
this.imgCal=$('#imgCal_'+this.valContId);},addValidation:function(type){if(type!="isRequired"){return false;}
this.superclass.addValidation.call(this,type);}});Runner.controls.DateTextField=Runner.extend(Runner.controls.DateField,{constructor:function(cfg){this.addEvent(["change","keyup"]);Runner.controls.DateTextField.superclass.constructor.call(this,cfg);if(cfg.disabled===true||cfg.disabled==="true"){this.setDisabled();}},getValue:function(){var parsedTime=parse_datetime(this.valueElem.val(),this.dateFormat);if(parsedTime==null){return"";}else{return parsedTime;}},setValue:function(newDate,triggerEvent){if(typeof newDate=='object'&&newDate!=null){var dt=print_datetime(newDate,this.dateFormat,this.showTime);this.valueElem.val(dt);if(this.useDatePicker){dt=print_datetime(newDate,-1,this.showTime);this.datePickerHiddElem.val(dt);}
this.validate();return true;}else{this.valueElem.val("");if(this.useDatePicker){this.datePickerHiddElem.val("");}
this.validate();return false;}
if(triggerEvent===true){this.fireEvent("change");}},"blur":function(e)
{this.stopEvent(e);var vRes=this.validate();if(vRes.result&&this.useDatePicker&&this.getValue())
this.setValue(this.getValue());},setDisabled:function()
{if(this.valueElem.get(0)&&this.imgCal)
{this.valueElem.get(0).disabled=true;this.imgCal.css('visibility','hidden');return true;}else{return false;}},setEnabled:function()
{if(this.valueElem.get(0))
{this.valueElem.get(0).disabled=false;if(this.imgCal!=null)
this.imgCal.css('visibility','visible');return true;}else{return false;}},getForSubmit:function(){return[this.valueElem.clone(),this.dateFormatHiddElem.clone()];},getStringValue:function(){var dateObj=this.getValue();if(dateObj===""){return"";}else{return dateObj.getFullYear()+'-'+(dateObj.getMonth()+1)+'-'+dateObj.getDate()+' '+dateObj.getHours()+':'+dateObj.getMinutes()+':'+dateObj.getSeconds();}}});Runner.controls.DateDropDown=Runner.extend(Runner.controls.DateField,{hiddValueElem:null,hiddElemId:"",constructor:function(cfg){cfg.stopEventInit=true;Runner.controls.DateDropDown.superclass.constructor.call(this,cfg);this.valueElem={"day":$("#day"+this.valContId),"month":$("#month"+this.valContId),"year":$("#year"+this.valContId)};if(cfg.disabled===true||cfg.disabled==="true"){this.setDisabled();}
this.defaultValue=this.getValue();this.addEvent(["change"]);this.killEvent("blur");this.elemsForEvent=[this.valueElem["day"].get(0),this.valueElem["month"].get(0),this.valueElem["year"].get(0)];this.init();this.hiddElemId=this.valContId;this.hiddValueElem=$("#"+this.hiddElemId);this.inputType="3dd";if(window.TEXT_MONTH_JAN){this.addYearOptions(cfg.yearVal);this.addMonthOptions(cfg.monthVal);this.addDayOptions(cfg.dayVal);}},destructor:function(){this.valueElem['day'].remove();this.valueElem['month'].remove();this.valueElem['year'].remove();},addYearOptions:function(selectedYear){this.valueElem["year"].html('');var dt=new Date();var currentYear=dt.getFullYear();var startYear=currentYear-100;var endYear=currentYear+10;var opt=document.createElement('OPTION');$(opt).val('').html('');this.valueElem["year"].append(opt);for(var i=startYear;i<=endYear;i++){var opt=document.createElement('OPTION');$(opt).val(i).html(i);if(i==selectedYear){opt.selected=true;}
this.valueElem["year"].append(opt);};this.addYearOptions=Runner.emptyFn;},addMonthOptions:function(selectedMonth){this.valueElem["month"].html('');var opt=document.createElement('OPTION');$(opt).val('').html('');this.valueElem["month"].append(opt);var monthNames=[];monthNames[1]=window.TEXT_MONTH_JAN;monthNames[2]=window.TEXT_MONTH_FEB;monthNames[3]=window.TEXT_MONTH_MAR;monthNames[4]=window.TEXT_MONTH_APR;monthNames[5]=window.TEXT_MONTH_MAY;monthNames[6]=window.TEXT_MONTH_JUN;monthNames[7]=window.TEXT_MONTH_JUL;monthNames[8]=window.TEXT_MONTH_AUG;monthNames[9]=window.TEXT_MONTH_SEP;monthNames[10]=window.TEXT_MONTH_OCT;monthNames[11]=window.TEXT_MONTH_NOV;monthNames[12]=window.TEXT_MONTH_DEC;for(var i=1;i<monthNames.length;i++){var opt=document.createElement('OPTION');$(opt).val(i).html(monthNames[i]);if(i==selectedMonth){opt.selected=true;}
this.valueElem["month"].append(opt);}
this.valueElem["month"].css('width','90px');this.addMonthOptions=Runner.emptyFn;},addDayOptions:function(selectedDay){this.valueElem["day"].html('');var opt=document.createElement('OPTION');$(opt).val('').html('');this.valueElem["day"].append(opt);for(var i=1;i<=31;i++){var opt=document.createElement('OPTION');$(opt).val(i).html(i);if(i==selectedDay){opt.selected=true;}
this.valueElem["day"].append(opt);};this.addDayOptions=Runner.emptyFn;},"change":function(e)
{this.stopEvent(e);var vRes=this.validate();if(vRes.result){this.setValue(this.getValue());}
return vRes;},"blur":Runner.emptyFn,getValue:function()
{if(this.valueElem["day"]&&this.valueElem["day"].val()){var dayVal=this.valueElem["day"].val();}else{return false;}
if(this.valueElem["month"]&&this.valueElem["month"].val()){var monthVal=this.valueElem["month"].val();}else{return false;}
if(this.valueElem["year"]&&this.valueElem["year"].val()){var yearVal=this.valueElem["year"].val();}else{return false;}
var date=new Date(yearVal,monthVal-1,dayVal,00,00,00);return date;},setValue:function(newDate,triggerEvent)
{if(typeof newDate=='object'&&newDate!=null)
{this.hiddValueElem.get(0).value=newDate.getFullYear()+'-'+(newDate.getMonth()+1)+'-'+newDate.getDate();this.valueElem["day"].get(0).selectedIndex=newDate.getDate();this.valueElem["month"].get(0).selectedIndex=newDate.getMonth()+1;for(var i=0;i<this.valueElem["year"].get(0).options.length;i++)
{if(this.valueElem["year"].get(0).options[i].value==newDate.getFullYear())
{this.valueElem["year"].get(0).selectedIndex=i;break;}}
if(this.useDatePicker)
this.datePickerHiddElem.get(0).value=newDate.getDate()+'-'+(newDate.getMonth()+1)+'-'+newDate.getFullYear();return true;}else{this.hiddValueElem.val('');if(this.isResetHappend)
{this.valueElem["day"].get(0).selectedIndex=0;this.valueElem["month"].get(0).selectedIndex=0;this.valueElem["year"].get(0).selectedIndex=0;}
if(this.useDatePicker){this.datePickerHiddElem.val("");}
return false;}
if(triggerEvent===true){this.fireEvent("change");}},setDisabled:function()
{if(!this.valueElem["day"]||!this.valueElem["month"]||!this.valueElem["year"]||!this.imgCal){return false;}
this.valueElem["day"][0].disabled=true;this.valueElem["month"][0].disabled=true;this.valueElem["year"][0].disabled=true;this.imgCal.css('visibility','hidden');return true;},setEnabled:function()
{this.valueElem["day"][0].disabled=false;this.valueElem["month"][0].disabled=false;this.valueElem["year"][0].disabled=false;if(this.imgCal!=null)
this.imgCal.css('visibility','visible');return true;},getForSubmit:function(){return[this.hiddValueElem.clone(),this.dateFormatHiddElem.clone()];},setFocus:function(triggerEvent){if(this.valueElem["day"].get(0).disabled!=true){this.valueElem["day"].get(0).focus();if(triggerEvent===true){this.fireEvent("focus");}
this.isSetFocus=true;return true;}else{this.isSetFocus=false;return false;}},isEmpty:function(){if(this.valueElem["day"].val()==""||this.valueElem["month"].val()==""||this.valueElem["year"].val()==""){return true;}else{return false;}},getStringValue:function(){return this.hiddValueElem.val();}});Runner.controls.RadioControl=Runner.extend(Runner.controls.Control,{radioElemsId:"",radioElemsArr:[],radioElemsNameAttr:"",radioElem:null,radioElemsCount:0,constructor:function(cfg){this.radioElemsArr=new Array();cfg.stopEventInit=true;Runner.controls.RadioControl.superclass.constructor.call(this,cfg);this.radioElemsId="radio_"+this.goodFieldName+"_"+this.id+"_";this.radioElemsNameAttr="radio_"+this.goodFieldName+"_"+this.id;this.radioElem=$('input[@name='+this.radioElemsNameAttr+']');this.radioElemsCount=this.radioElem.length;for(var i=0;i<this.radioElemsCount;i++){this.radioElemsArr.push($("#"+this.radioElemsId+i));this.elemsForEvent.push(this.radioElemsArr[i].get(0));}
if(cfg.disabled==true||cfg.disabled=="true"){this.setDisabled();}
this.addEvent(["click"]);this.init();},setValue:function(val,triggerEvent){var choosen=false;for(var i=0;i<this.radioElemsCount;i++){if(this.radioElemsArr[i].val()==val){this.radioElemsArr[i].get(0).checked=true;this.valueElem.val(val);choosen=true;}else{this.radioElemsArr[i].get(0).checked=false;}}
if(triggerEvent===true){this.fireEvent("change");}
return choosen;},setDisabled:function(){for(var i=0;i<this.radioElemsCount;i++){this.radioElemsArr[i].get(0).disabled=true;}
return true;},setEnabled:function(){for(var i=0;i<this.radioElemsCount;i++){this.radioElemsArr[i].get(0).disabled=false;}
return true;},"blur":Runner.emptyFn,"click":function(e){if(e.target.value!=this.getValue()){this.setValue(e.target.value,false);return this.validate().result;}else{return true;}}});Runner.controls.LookupWizard=Runner.extend(Runner.controls.Control,{isLookupWizard:true,dependentCtrls:[],parentCtrl:null,parentFieldName:'',constructor:function(cfg){cfg.stopEventInit=true;this.dependentCtrls=new Array();Runner.controls.LookupWizard.superclass.constructor.call(this,cfg);this.addNew=$("#addnew_"+this.valContId);this.addEvent(["change"]);},destructor:function(){delete this.dependentCtrls;},addDependentCtrls:function(ctrlsArr){for(var i=0;i<ctrlsArr.length;i++){this.dependentCtrls.push(ctrlsArr[i]);}},clearChildrenLinks:function(triggerReload){for(var i=0;i<this.dependentCtrls.length;i++){if(this.dependentCtrls[i]){this.dependentCtrls[i].clearParent(triggerReload);}}},clearParent:function(triggerReload){this.parentCtrl=null;if(triggerReload===true){this.reload();}},setParentCtrl:function(ctrl){this.parentCtrl=ctrl;},reloadDependeces:function(){var masterCtrlVal=this.getValue();masterCtrlVal=typeof(masterCtrlVal)=='object'?masterCtrlVal[0]:masterCtrlVal;for(var i=0;i<this.dependentCtrls.length;i++){if(this.dependentCtrls[i]){this.dependentCtrls[i].reload(masterCtrlVal);}}},clearInvalidOnDependences:function(){for(var i=0;i<this.dependentCtrls.length;i++){if(this.dependentCtrls[i]){this.dependentCtrls[i].clearInvalid();}}},parseContentToValues:function(txt){if(txt.length==0){return false;}
return txt.split('\n');},"change":function(e){this.clearInvalidOnDependences();var vRes=this.validate();if(vRes.result){this.reloadDependeces();return true;}else{return false;}}});Runner.controls.DropDownLookup=Runner.extend(Runner.controls.LookupWizard,{multiSel:1,optionsDOM:[],constructor:function(cfg){this.multiSel=cfg.multiSel?cfg.multiSel:1;Runner.controls.DropDownLookup.superclass.constructor.call(this,cfg);this.inputType="select";this.defaultValue=this.getValue(true);this.elemsForEvent=[this.valueElem.get(0)];this.init();this.optionsDOM=this.valueElem.get(0).options;if(cfg.disabled==true||cfg.disabled=="true"){this.setDisabled();}},setValue:function(vals,triggerEvent)
{var choosen=0;for(var i=0;i<this.valueElem.get(0).options.length;i++){for(var j=0;j<vals.length;j++){if(this.valueElem.get(0).options[i].value==vals[j]){this.optionsDOM[i].selected=true;choosen++;if(this.multiSel==1){this.valueElem.get(0).selectedIndex=i;}else{break;}}else{this.optionsDOM[i].selected=false;}}
if(choosen>0&&this.multiSel==1){break;}}
if(triggerEvent===true){this.fireEvent("change");}
if(choosen==vals.length&&choosen<=this.multiSel){return true;}else{return false;}},getValue:function(returnArray)
{var selVals=[];if(this.optionsDOM.length)
{for(var i=0;i<this.optionsDOM.length;i++)
{if(this.optionsDOM[i].selected)
selVals.push(this.optionsDOM[i].value)}}
else{for(var i=0;i<this.valueElem.get(0).options.length;i++)
{if(this.valueElem.get(0).options[i].selected)
selVals.push(this.valueElem.get(0).options[i].value);}}
if(returnArray===true)
return selVals;if(selVals.length>1)
return selVals;else if(selVals.length==1)
return selVals[0];else
return"";},isEmpty:function(){var selVals=this.getValue();if(typeof selVals!='object')
return selVals==="";return false;},clearOptions:function(){this.valueElem.empty();},addOption:function(text,val){this.optionsDOM[this.optionsDOM.length]=new Option(unescape(text),unescape(val));},addOptionsArr:function(optionsArr){for(var i=0;i<optionsArr.length-1;i=i+2){this.addOption(optionsArr[i+1],optionsArr[i]);}},preload:function(txt,selectValue){var parsedOptionsContent=this.parseContentToValues(txt),parsedSelected=this.parseContentToValues(selectValue);this.clearOptions();if(this.multiSel==1){this.addOption(TEXT_PLEASE_SELECT,"");}
this.addOptionsArr(parsedOptionsContent);if(this.optionsDOM.length==2){this.setValue([this.optionsDOM[1].value],false);}else if(this.optionsDOM.length>0){this.setValue([this.optionsDOM[0].value],false);}
this.setValue([selectValue],false);},reload:function(masterCtrlValue){var fName=this.fieldName,tName=this.table,rowId=this.id;if(masterCtrlValue&&!this.parentCtrl){return false;}
var ajaxParams={field:myEncode(fName),value:myEncode((masterCtrlValue!==undefined?masterCtrlValue:'')),isExistParent:(this.parentCtrl?1:0),type:this.valueElem[0].tagName,mode:this.mode,rndVal:(new Date().getTime())};var ctrl=this;$.get(this.shortTableName+"_autocomplete.php",ajaxParams,function(txt,textStatus){ctrl.clearOptions();if(ctrl.multiSel==1){ctrl.addOption(TEXT_PLEASE_SELECT,"");}
var parsedOptionsContent=ctrl.parseContentToValues(txt);if(parsedOptionsContent){ctrl.addOptionsArr(parsedOptionsContent);}
if(ctrl.optionsDOM.length==2){ctrl.setValue([ctrl.optionsDOM[1].value],false);}else if(ctrl.optionsDOM.length>0){ctrl.setValue([ctrl.optionsDOM[0].value],false);}
ctrl.fireEvent("change");ctrl.clearInvalid();});},setDisabled:function()
{if(this.valueElem)
{this.valueElem.get(0).disabled=true;if(this.addNew){this.addNew.css('visibility','hidden');}
return true;}
return false;},setEnabled:function()
{if(this.valueElem)
{this.valueElem.get(0).disabled=false;if(this.addNew){this.addNew.css('visibility','visible');}
return true;}else{return false;}},getForSubmit:function()
{var clone=this.valueElem.clone(),selVals=this.getValue(true);var cloneOpt=clone.get(0).options;for(var i=0;i<cloneOpt.length;i++)
{for(var j=0;j<selVals.length;j++)
{if(cloneOpt[i].value==selVals[j])
{if(this.multiSel==1)
clone.get(0).selectedIndex=i;cloneOpt[i].selected=true;}
else
{cloneOpt.selected=false;}}}
return[clone];},"blur":Runner.emptyFn});Runner.controls.CheckBoxLookup=Runner.extend(Runner.controls.LookupWizard,{typeElemId:"",typeElem:null,checkBoxCount:0,checkBoxesArr:[],checkBoxNameAttr:"",constructor:function(cfg){this.checkBoxesArr=[];Runner.controls.CheckBoxLookup.superclass.constructor.call(this,cfg);this.inputType="checkbox";this.typeElemId="type_"+this.goodFieldName+"_"+this.id;this.typeElem=$("#"+this.typeElemId);this.dataCheckBoxId="data_"+this.valContId;if(($("#"+this.valContId)).length){var checkBox=$("#"+this.valContId);this.checkBoxesArr.push(checkBox);this.elemsForEvent.push(this.checkBoxesArr[0].get(0));}else{var checkBox,i=0;while(($("#"+this.valContId+"_"+i)).length){checkBox=$("#"+this.valContId+"_"+i);this.checkBoxesArr.push(checkBox);this.elemsForEvent.push(this.checkBoxesArr[i].get(0));i++;}}
if(cfg.disabled==true||cfg.disabled=="true"){this.setDisabled();}
this.addEvent(["click"]);this.init();this.defaultValue=this.getValue();this.checkBoxNameAttr='value_'+this.goodFieldName+'_'+this.id;this.valueElem=$('input[@name^='+this.checkBoxNameAttr+']');},setValue:function(valsArr,triggerEvent){var checkCount=0;for(var i=0;i<this.checkBoxesArr.length;i++){this.checkBoxesArr[i].get(0).checked=false;for(var j=0;j<valsArr.length;j++){if(this.checkBoxesArr[i].val()==valsArr[j]){this.checkBoxesArr[i].get(0).checked=true;checkCount++;break;}}}
if(triggerEvent===true){this.fireEvent("click");}
if(checkCount==valsArr.length&&checkCount<=this.checkBoxesArr.length&&valsArr.length<=this.checkBoxesArr.length){return true;}else{return false;}},getValue:function(){var checkedArr=this.getCheckedBoxes(),valsArr=[];for(var i=0;i<checkedArr.length;i++){valsArr.push(checkedArr[i].val());}
return valsArr;},isEmpty:function(){if(this.getValue().length==0){return true;}else{return false;}},setDisabled:function(){for(var i=0;i<this.checkBoxesArr.length;i++){this.checkBoxesArr[i].get(0).disabled=true;}
return true;},setEnabled:function(){for(var i=0;i<this.checkBoxesArr.length;i++){this.checkBoxesArr[i].get(0).disabled=false;}
return true;},setDisabledShowCheckedBoxes:function()
{for(var i=0;i<this.checkBoxesArr.length;i++)
{if(this.checkBoxesArr[i].get(0).checked)
this.checkBoxesArr[i].get(0).disabled=true;else{var dataId=$('#'+this.dataCheckBoxId+'_'+i);this.checkBoxesArr[i].css("display","none");dataId.css("display","none");dataId.next().css("display","none");}}
return true;},getCheckedBoxes:function(){var chekedArr=[];for(var i=0;i<this.checkBoxesArr.length;i++){if(this.checkBoxesArr[i].get(0).checked){chekedArr.push(this.checkBoxesArr[i]);}}
return chekedArr;},getForSubmit:function(){var checkedArr=this.getCheckedBoxes(),cloneArr=[];for(var i=0;i<checkedArr.length;i++){var realCb=checkedArr[i];var readioClone=document.createElement('input');$(readioClone).attr('type','hidden');$(readioClone).attr('id',realCb.attr('id'));$(readioClone).attr('name',realCb.attr('name'));$(readioClone).val(realCb.val());cloneArr.push(readioClone);}
cloneArr.push(this.typeElem);return cloneArr;},clearCheckBoxes:function(){for(var i=0;i<this.checkBoxesArr.length;i++){this.checkBoxesArr[i].remove();}
this.checkBoxesArr=[];},addCheckBox:function(text,val){var newCheckBoxId=this.valContId+"_"+this.checkBoxesArr.length;this.spanContElem.find('div').append('<input type="checkbox" id="'+newCheckBoxId+'" name="'+newCheckBoxId+'[]" value="val">'+text+'<br/>');this.checkBoxesArr.push($("#"+newCheckBoxId));},addCheckBoxArr:function(optionsArr){for(var i=0;i<optionsArr.length-1;i=i+2){this.addOption(optionsArr[i+1],optionsArr[i]);}},preload:function(txt,selectValue){var parsedOptionsContent=this.parseContentToValues(txt),parsedSelected=this.parseContentToValues(selectValue);this.clearCheckBoxes();this.addCheckBoxArr(parsedOptionsContent);if(this.checkBoxesArr.length==1){this.setValue([this.checkBoxesArr[0].val()],false);}
this.setValue([selectValue],false);},reload:function(masterCtrlValue){var fName=this.fieldName,tName=this.table,rowId=this.id;var ajaxParams={field:myEncode(fName),value:myEncode(masterCtrlValue),type:this.valueElem[0].tagName,rndVal:(new Date().getTime())};$.get(this.shortTableName+"_autocomplete.php",ajaxParams,function(txt,textStatus){var ctrl=Runner.controls.ControlManager.getAt(tName,rowId,fName);ctrl.clearOptions();var parsedOptionsContent=ctrl.parseContentToValues(txt);if(parsedOptionsContent===false){return false;}
ctrl.addOptionsArr(parsedOptionsContent);if(ctrl.checkBoxesArr.length==1){ctrl.setValue([ctrl.checkBoxesArr[0].val()],false);}
ctrl.fireEvent("change");ctrl.clearInvalid();});},"blur":Runner.emptyFn,"click":this["change"]});Runner.controls.TextFieldLookup=Runner.extend(Runner.controls.LookupWizard,{displayId:"",displayElem:null,constructor:function(cfg){Runner.controls.TextFieldLookup.superclass.constructor.call(this,cfg);this.displayId="display_"+this.valContId;this.displayElem=$("#"+this.displayId);this.inputType="text";this.elemsForEvent=[this.displayElem.get(0)];if(cfg.disabled==true||cfg.disabled=="true"){this.setDisabled();}
this.defaultValue=[this.getValue(),this.getDisplayValue()];},setDisplayValue:function(val){if(this.displayElem){return this.displayElem.val(val);}else{return false;}},getDisplayValue:function(){if(this.displayElem){return this.displayElem.val();}else{return false;}},setValue:function(dispVal,hiddVal,triggerEvent){var changed=false;if(this.valueElem.val()!=hiddVal)
changed=true;var isSetHiddVal=this.valueElem.val(hiddVal);if(isSetHiddVal===false){return false;}
if(this.getDisplayValue()!=dispVal)
changed=true;var isSetDispVal=this.setDisplayValue(dispVal);if(isSetDispVal===false){return false;}
if(changed&&triggerEvent===true){this.fireEvent("change");}
return changed;},getValue:function(){return this.valueElem.val();},reset:function(){this.setValue(this.defaultValue[1],this.defaultValue[0]);this.clearInvalid();return true;},setDisabled:function(){if(this.displayElem){this.displayElem.get(0).disabled=true;return true;}else{return false;}},setEnabled:function(){if(this.displayElem){this.displayElem.get(0).disabled=false;return true;}else{return false;}},setFocus:function(triggerEvent){if(this.displayElem.get(0).disabled!=true){this.displayElem.get(0).focus();if(triggerEvent===true){this.fireEvent("focus");}
this.isSetFocus=true;return true;}else{this.isSetFocus=false;return false;}},removeCSS:function(className){this.displayElem.removeClass(className);},addCSS:function(className){this.displayElem.addClass(className);},getAttr:function(attrName){return this.displayElem.attr(attrName);},getDispElem:function(){return this.displayElem;},isEmpty:function(){return this.getDisplayValue().toString()=="";},preload:function(txt,selectValue){var parsedOptionsContent=this.parseContentToValues(txt);for(var i=0;i<parsedOptionsContent.length-1;i=i+2){if(unescape(parsedOptionsContent[i])==selectValue){this.setValue(parsedOptionsContent[i+1],parsedOptionsContent[i]);}}},reload:function(masterCtrlValue){var fName=this.fieldName,tName=this.table,rowId=this.id;if(masterCtrlValue&&!this.parentCtrl){return false;}
var ajaxParams={field:myEncode(fName),value:myEncode(masterCtrlValue),isExistParent:(this.parentCtrl?1:0),mode:this.mode,type:this.valueElem[0].tagName,rndVal:(new Date().getTime())};var ctrl=this;$.get(this.shortTableName+"_autocomplete.php",ajaxParams,function(txt,reqStatus){var parsedOptionsContent=ctrl.parseContentToValues(txt);if(parsedOptionsContent.length==3){if(ctrl.getValue()!=parsedOptionsContent[0]){ctrl.setValue(parsedOptionsContent[1],parsedOptionsContent[0],true);}else{ctrl.setValue(parsedOptionsContent[1],parsedOptionsContent[0]);}}else{ctrl.setValue("","",true);}
ctrl.clearInvalid();});}});Runner.controls.EditBoxLookup=Runner.extend(Runner.controls.TextFieldLookup,{focusState:false,isLookupError:false,cursor:-1,suggestValues:null,lookupValues:null,lookupDivId:"",lookupDiv:null,lookupIframeId:"",lookupIframe:null,constructor:function(cfg){this.lookupValues=[];this.suggestValues=[];Runner.controls.EditBoxLookup.superclass.constructor.call(this,cfg);this.lookupDivId='lookupSuggest_'+this.valContId;if(Runner.isIE6){this.lookupIframeId='iFrame_'+this.valContId;}
this.addEvent(["keyup","focus","keydown","blur"]);this.init();},destructor:function(){Runner.controls.EditBoxLookup.superclass.destructor.call(this);this.destroyDiv();},checkKeyCodeForRunSuggest:function(keyCode){return(((keyCode>=65)&&(keyCode<=90))||((keyCode>=48)&&(keyCode<=57))||((keyCode>=96)&&(keyCode<=105))||(keyCode==8)||(keyCode==46)||(keyCode==32)||(keyCode==222));},"keyup":function(e){this.stopEvent(e);if(this.getDisplayValue()==""){this.destroyDiv();this.isLookupError=false;this.removeCSS("highlight");this.setValue("","",true);return;}
if(e&&this.checkKeyCodeForRunSuggest(e.keyCode)){this.lookupAjax();}},"keydown":function(e){var keyCode=e.keyCode;switch(keyCode){case 38:this.moveUp();break;case 40:this.moveDown();break;case 13:this.destroyDiv();this.stopEvent(e);return false;break;case 9:this.destroyDiv();break;}
return true;},showDiv:function(lookupSuggestHtml){this.destroyDiv();$(document).find('body').append('<div id="'+this.lookupDivId+'" class="search_suggest">'+lookupSuggestHtml+'</div>');if(Runner.isIE6){$(document).find('body').append('<iframe src="javascript:false;" id="'+this.lookupIframeId+'" frameborder="1" vspace="0" hspace="0" marginwidth="0" marginheight="0" scrolling="no" style="background:white;position:absolute;display:block;opacity:0;filter:alpha(opacity=0);"></iframe>');this.lookupIframe=$("#"+this.lookupIframeId);}
this.lookupDiv=$("#"+this.lookupDivId);this.setDivPos();this.lookupDiv.css("visibility","visible")},destroyDiv:function(){if(this.lookupDiv){this.lookupDiv.remove();}
if(Runner.isIE6&&this.lookupIframe){this.lookupIframe.remove();this.lookupIframe=null;}
this.cursor=-1;this.lookupDiv=null;},setDivPos:function(){var coors=findPos(this.getDispElem().get(0));coors[1]+=coors[3];this.lookupDiv.css("top",coors[1]+"px");this.lookupDiv.css("left",coors[0]+"px");if(Runner.isIE){this.lookupDiv.css("zIndex",++zindex_max);}else{this.lookupDiv.css("z-index",++zindex_max);}
if(Runner.isIE6&&this.lookupIframe){this.lookupIframe.css("top",coors[1]+"px");this.lookupIframe.css("left",coors[0]+"px");this.lookupIframe.css("width",this.lookupDiv.css("width"));this.lookupIframe.css("height",this.lookupDiv.css("height"));}},suggestOver:function(divHovered){this.lookupDiv.find("div.suggest_link_over").each(function(){this.className='suggest_link';});divHovered.className='suggest_link_over';this.cursor=divHovered.id.substring(10);},suggestOut:function(divValue){divValue.className='suggest_link';},lookupAjax:function(){var table=this.table,recId=this.id,fName=this.fieldName,ctrl=this;var ajaxParams={mode:this.mode,table:this.shortTableName,searchFor:myEncode(this.getDisplayValue()),searchField:myEncode(this.goodFieldName),lookupValue:myEncode(this.getValue()),category:(this.parentCtrl?this.parentCtrl.getValue():""),rndVal:(new Date().getTime())}
$.get("lookupsuggest.php",ajaxParams,function(txt,textStatus){if(!txt.trim()){this.isLookupError=true;if(ctrl.focusState){ctrl.addCSS("highlight");}
return false;}
var hiddVal=ctrl.getValue(),dispVal=ctrl.getDisplayValue(),valArr=[ctrl.getValue(),ctrl.getDisplayValue()];var str=txt.split("\n");$.each(str,function(i,n){str[i]=unescape(n);})
if(hiddVal!=""&&str.isInArray(hiddVal)){this.isLookupError=false;ctrl.removeCSS("highlight");$.each(str,function(i,n){if((n.toLowerCase()==valArr[1])&&(str[i-1]!=valArr[0])){ctrl.setValue(valArr[1],str[i-1],true);}});}
var suggest="";for(var i=0,j=0;i<str.length-1;i=i+2,j++){suggest+='<div id="suggestDiv'+i+'" style="cursor:pointer;" onmouseover="'+'var ctrl = Runner.controls.ControlManager.getAt(\''+table+'\', '+recId+', \''+fName+'\', 0);'+'ctrl.suggestOver(this);" '+'onmouseout="var ctrl = Runner.controls.ControlManager.getAt(\''+table+'\', '+recId+', \''+fName+'\', 0);'+'ctrl.suggestOut(this);" '+'onclick="var ctrl = Runner.controls.ControlManager.getAt(\''+table+'\', '+recId+', \''+fName+'\', 0);'+'ctrl.isLookupError = false;'+'ctrl.removeCSS(\'highlight\');'+'ctrl.setValue(ctrl.suggestValues['+j+'], \''+str[i]+'\', true);'+'ctrl.destroyDiv();" '+'class="suggest_link">'+str[i+1]+'</div>';ctrl.suggestValues[j]=str[i+1];ctrl.lookupValues[j]=str[i];}
ctrl.showDiv(suggest);ctrl.setDivPos();});},moveDown:function(){if(!this.lookupDiv)
return;if(this.lookupDiv.children().length>0&&this.cursor<this.lookupDiv.children().length){this.cursor++;for(var i=0;i<this.lookupDiv.children().length;i++){if(i==this.cursor){this.isLookupError=false;this.removeCSS("highlight");this.lookupDiv.children().get(i).className="suggest_link_over";var suggestVal=this.suggestValues[this.cursor].replace(/\<(\/b|b)\>/gi,""),lookupVal=this.lookupValues[this.cursor];if(this.getValue()!=lookupVal){this.setValue(suggestVal,lookupVal,true);}else{this.setValue(suggestVal,lookupVal);}}
else{this.lookupDiv.children().get(i).className="suggest_link";}}
if(this.cursor==(this.lookupDiv.children().length)){this.cursor=-1;this.focus();}}},moveUp:function(){if(!this.lookupDiv)
return;if(this.lookupDiv.children().length>0&&this.cursor>=-1){this.cursor--;if(this.cursor==-2){this.cursor=this.lookupDiv.children().length-1;this.focus();}
for(var i=0;i<this.lookupDiv.children().length;i++){if(i==this.cursor){this.lookupDiv.children().get(i).className="suggest_link_over";var suggestVal=this.suggestValues[this.cursor].replace(/\<(\/b|b)\>/gi,""),lookupVal=this.lookupValues[this.cursor];if(this.getValue()!=lookupVal){this.setValue(suggestVal,lookupVal,true);}else{this.setValue(suggestVal,lookupVal);}
this.isLookupError=false;this.removeCSS("highlight");}
else{this.lookupDiv.children().get(i).className="suggest_link";}}}},setDisabled:function()
{var res=Runner.controls.EditBoxLookup.superclass.setDisabled.call(this);if(res){this.addNew.css('visibility','hidden');}
return res;},setEnabled:function()
{var res=Runner.controls.EditBoxLookup.superclass.setEnabled.call(this);if(res){this.addNew.css('visibility','visible');}
return res;},"blur":function(e){if(this.getDisplayValue()!=''&&!this.suggestValues.isInArray(this.getDisplayValue())){this.suggestValues.push(this.getDisplayValue());}
if(this.getValue()!=''&&!this.lookupValues.isInArray(this.getValue())){this.lookupValues.push(this.getValue());}
this["blur"]=function(e){this.focusState=false;if(!this.suggestValues.isInArray(this.getDisplayValue())||this.isLookupError){this.addCSS("highlight");}else{this.removeCSS("highlight");}
var ctrl=this;var destroyDiv=function(){ctrl.destroyDiv();};setTimeout(destroyDiv,150);Runner.controls.EditBoxLookup.superclass["blur"].call(this,e);};this["blur"](e);},"focus":function(e){this.stopEvent(e);this.focusState=true;},setValue:function(dispVal,hiddVal,triggerEvent){var changed=Runner.controls.EditBoxLookup.superclass.setValue.call(this,dispVal,hiddVal,triggerEvent);if(changed&&triggerEvent===true){this.changeTrigger(null);}},changeTrigger:function(e){Runner.controls.EditBoxLookup.superclass.constructor.superclass["change"].call(this,e);},"change":Runner.emptyFn});Runner.controls.ListPageLookup=Runner.extend(Runner.controls.TextFieldLookup,{selectLinkId:"",selectLinkElem:null,lookupVals:null,selectField:'',isLookupOpen:false,pageId:-1,constructor:function(cfg){Runner.controls.ListPageLookup.superclass.constructor.call(this,cfg);this.init();this.selectLinkId="open_lookup_"+this.goodFieldName+"_"+this.id;this.selectLinkElem=$("#"+this.selectLinkId);if(cfg.disabled==true||cfg.disabled=="true"){this.setDisabled();}},setDisabled:function()
{var res=Runner.controls.ListPageLookup.superclass.setDisabled.call(this);if(res){if(this.selectLinkElem){this.selectLinkElem.css('visibility','hidden');}}
return res;},setEnabled:function()
{var res=Runner.controls.ListPageLookup.superclass.setEnabled.call(this);if(res){if(this.selectLinkElem){this.selectLinkElem.css('visibility','visible');}}
return res;},setLookupVal:function(valInd){this.setValue(this.lookupVals[valInd].dispVal,this.lookupVals[valInd].linkVal,true);},addLookupVal:function(linkVal,dispVal){return(this.lookupVals.push({'linkVal':linkVal,'dispVal':dispVal})-1);},initLink:function(link,ind,winId){var ctrl=this;link.bind('click',function(e){ctrl.stopEvent(e);ctrl.setLookupVal(ind);RemoveFlyDiv(winId);});},initLinks:function(winId){var links=$("a[@type='lookupSelect"+winId+"']");for(var i=0;i<links.length;i++){this.initLink($(links[i]),i,winId);}},showPage:function(event,page,control,category){this.stopEvent(event);var lookuPage=$('#fly'+this.pageId);if(lookuPage.length==0){this.pageId=DisplayPage(event,page,this.id,control,this.fieldName,this.table,category);}else{lookuPage.css('z-index',++window.zindex_max);$('#shadow'+this.pageId).css('z-index',window.zindex_max);}}});function AddEventRegControl(tName,fields,id,passName){var passCntrl=Runner.controls.ControlManager.getAt(tName,id,passName);var confCntrl=Runner.controls.ControlManager.getAt(tName,id,'confirm');passCntrl.on('blur',function(e,argsArr){if(argsArr[0].getValue()!=this.getValue()&&argsArr[0].getValue()!=""){argsArr[0].markInvalid([window.PASSWORDS_DONT_MATCH]);}else{argsArr[0].clearInvalid();this.clearInvalid();}},{args:[confCntrl]});confCntrl.on('blur',function(e,argsArr){if(argsArr[0].getValue()!=this.getValue()){this.markInvalid([window.PASSWORDS_DONT_MATCH]);}else{argsArr[0].clearInvalid();this.clearInvalid();}},{args:[passCntrl]});for(var i=0;i<fields.length;i++){if(fields[i]=='confirm'||fields[i-1]==passName){continue;}
var Cntrl=Runner.controls.ControlManager.getAt(tName,id,fields[i]);var args=new Array(fields[i]);Cntrl.on('blur',function(e,argsArr){params={id:id,rndval:Math.random(),field:argsArr[0],val:this.getValue()};var Cntrl=this;$.get('registersuggest.php',params,function(xml){if(xml){Cntrl.markInvalid([xml]);}});},{args:args});}}
function AddEventForControl(tName,func,id)
{var arrCntrl=Runner.controls.ControlManager.getAt(tName);var args=[id];setEventForControl(arrCntrl,func,args);for(var i=0;i<arrCntrl.length;i++)
{if(arrCntrl[i].setFocus())
break;}}
function setEventForControl(arrCntrl,func,args)
{for(var i=0;i<arrCntrl.length;i++)
{var cntrlType=arrCntrl[i].getControlType(),eventName='change',singleFire=false,delay=0;if(cntrlType=='checkbox'||cntrlType=='radio')
{eventName='click';}
else if(cntrlType=='text'||cntrlType=='password'||cntrlType=='textarea')
{eventName='keyup';delay=60;arrCntrl[i].on('change',func,{single:true,timeout:0,args:args});}
else if(cntrlType=='RTE')
{eventName='blur';delay=5000;}
arrCntrl[i].on(eventName,func,{single:singleFire,timeout:delay,args:args});}}
function clearEventForControl(arrCntrl)
{for(var i=0;i<arrCntrl.length;i++)
{var cntrlType=arrCntrl[i].getControlType(),eventName='change';if(cntrlType=='checkbox'||cntrlType=='radio')
eventName='click';else if(cntrlType=='text'||cntrlType=='password'||cntrlType=='textarea')
{eventName='keyup';arrCntrl[i].clearEvent('change');}
else if(cntrlType=='RTE')
eventName='blur';arrCntrl[i].clearEvent(eventName);}}
function prevNextButtonHandler(e,argsArr)
{if(e&&(e.type=='keyup'||e.type=='keypress'||e.type=='keydown'))
{if(e.keyCode>=33&&e.keyCode<=40||e.keyCode==9)
return true;}
var prev=$('#prev'+argsArr[0])[0];var next=$('#next'+argsArr[0])[0];if(prev)
{$(prev).css('background','#dcdcdc url(\"images/sortprev.gif\") center no-repeat');$(prev).css('color','#dcdcdc');$(prev).css('cursor','default');$(prev).attr('disabled','disabled');}
if(next)
{$(next).css('background','#dcdcdc url(\"images/sortnext.gif\") center no-repeat');$(next).css('color','#dcdcdc');$(next).css('cursor','default');$(next).attr('disabled','disabled');}
return true;}